//Flexcel Centralized Configuration file
//Modify the defines in this file to fit your needs.

//Define your language by deleting the "." in the language you want to use.
//If you don't define one, english will be used
{.$DEFINE SPANISH}
{.$DEFINE FRENCH}
{.$DEFINE ITALIAN}
{.$DEFINE ROMANIAN}
{.$DEFINE PORTUGUESEBR}
{.$DEFINE CHINESE}
{.$DEFINE RUSSIAN}
{.$DEFINE GERMAN}
{.$DEFINE POLISH}
{.$DEFINE FINNISH}



