/************************************************************
*
* ElevateDB SQL Script for the DMSample database (Unicode)
*
************************************************************/


/************************************************************
* Tables
************************************************************/

SCRIPT ()
BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE "rbField"
                      (
                      "TableName" VARCHAR(60) COLLATE "UNI",
                      "FieldName" VARCHAR(60) COLLATE "UNI",
                      "FieldAlias" VARCHAR(60) COLLATE "UNI",
                      "Selectable" VARCHAR(1) COLLATE "UNI",
                      "Searchable" VARCHAR(1) COLLATE "UNI",
                      "Sortable" VARCHAR(1) COLLATE "UNI",
                      "DataType" VARCHAR(60) COLLATE "UNI",
                      "AutoSearch" VARCHAR(1) COLLATE "UNI",
                      "Mandatory" VARCHAR(1) COLLATE "UNI",
                      CONSTRAINT "PrimaryKey" PRIMARY KEY ("TableName", "FieldName")
                      )
                      VERSION 1
                      UNENCRYPTED
                      INDEX PAGE SIZE 4096
                      BLOB BLOCK SIZE 512
                      MAX ROW BUFFER SIZE 32768
                      MAX INDEX BUFFER SIZE 65536
                      MAX BLOB BUFFER SIZE 32768';
   EXECUTE IMMEDIATE 'CREATE TABLE "rbFolder"
                      (
                      "FolderId" INTEGER GENERATED BY DEFAULT AS IDENTITY,
                      "Name" VARCHAR(60) COLLATE "UNI",
                      "ParentId" INTEGER,
                      CONSTRAINT "PrimaryKey" PRIMARY KEY ("FolderId")
                      )
                      VERSION 1
                      UNENCRYPTED
                      INDEX PAGE SIZE 4096
                      BLOB BLOCK SIZE 512
                      MAX ROW BUFFER SIZE 32768
                      MAX INDEX BUFFER SIZE 65536
                      MAX BLOB BUFFER SIZE 32768';
   EXECUTE IMMEDIATE 'CREATE INDEX "ixParentId" ON "rbFolder"
                      ("ParentId")';
   EXECUTE IMMEDIATE 'CREATE TABLE "rbItem"
                      (
                      "ItemId" INTEGER GENERATED BY DEFAULT AS IDENTITY,
                      "FolderId" INTEGER,
                      "Name" VARCHAR(60) COLLATE "UNI",
                      "Size" INTEGER,
                      "ItemType" INTEGER,
                      "Modified" TIMESTAMP,
                      "Deleted" TIMESTAMP,
                      "Template" BLOB,
                      CONSTRAINT "PrimaryKey" PRIMARY KEY ("ItemId")
                      )
                      VERSION 1
                      UNENCRYPTED
                      INDEX PAGE SIZE 4096
                      BLOB BLOCK SIZE 512
                      MAX ROW BUFFER SIZE 32768
                      MAX INDEX BUFFER SIZE 65536
                      MAX BLOB BUFFER SIZE 32768';
   EXECUTE IMMEDIATE 'CREATE INDEX "ixFolderIdItemTypeName" ON "rbItem"
                      ("FolderId", "ItemType", "Name" COLLATE "UNI_CI")';
   EXECUTE IMMEDIATE 'CREATE TABLE "rbJoin"
                      (
                      "TableName1" VARCHAR(60) COLLATE "UNI_CI",
                      "TableName2" VARCHAR(60) COLLATE "UNI_CI",
                      "JoinType" VARCHAR(20) COLLATE "UNI",
                      "FieldNames1" VARCHAR(250) COLLATE "UNI",
                      "FieldNames2" VARCHAR(250) COLLATE "UNI",
                      "Operators" VARCHAR(60) COLLATE "UNI",
                      CONSTRAINT "PrimaryKey" PRIMARY KEY ("TableName1", "TableName2"),
                      CONSTRAINT "ix_TableName2TableName1" UNIQUE ("TableName2", "TableName1")
                      )
                      VERSION 1
                      UNENCRYPTED
                      INDEX PAGE SIZE 4096
                      BLOB BLOCK SIZE 512
                      MAX ROW BUFFER SIZE 32768
                      MAX INDEX BUFFER SIZE 65536
                      MAX BLOB BUFFER SIZE 32768';
   EXECUTE IMMEDIATE 'CREATE TABLE "rbTable"
                      (
                      "TableName" VARCHAR(60) COLLATE "UNI",
                      "TableAlias" VARCHAR(60) COLLATE "UNI",
                      CONSTRAINT "PrimaryKey" PRIMARY KEY ("TableName")
                      )
                      VERSION 1
                      UNENCRYPTED
                      INDEX PAGE SIZE 4096
                      BLOB BLOCK SIZE 512
                      MAX ROW BUFFER SIZE 32768
                      MAX INDEX BUFFER SIZE 65536
                      MAX BLOB BUFFER SIZE 32768';
END
   

/************************************************************
* End of generated SQL
************************************************************/

