{***************************************************************}
{ FIBPlus - component library for direct access to Firebird and }
{ InterBase databases                                           }
{                                                               }
{    FIBPlus is based in part on the product                    }
{    Free IB Components, written by Gregory H. Deatz for        }
{    Hoagland, Longo, Moran, Dunst & Doukas Company.            }
{    mailto:gdeatz@hlmdd.com                                    }
{                                                               }
{    Copyright (c) 1998-2007 Devrace Ltd.                       }
{    Written by Serge Buzadzhy (buzz@devrace.com)               }
{                                                               }
{ ------------------------------------------------------------- }
{    FIBPlus home page: http://www.fibplus.com/                 }
{    FIBPlus support  : http://www.devrace.com/support/         }
{ ------------------------------------------------------------- }
{                                                               }
{  Please see the file License.txt for full license information }
{***************************************************************}

// {$DEFINE USE_SYN_EDIT}
// {$DEFINE SYNEDIT_08_2001}
//{$DEFINE SYNEDIT_05_2004}
//{$DEFINE SYNEDIT_1.3}

{$DEFINE synedit-201b.zip}  // Archive File  from Synedit site

{$IFDEF synedit-201b.zip}
 {$DEFINE SYNEDIT_05_2004}
 {$DEFINE SYNEDIT_1.3}
{$ENDIF}
//Use SynEdit:  (http://synedit.sourceforge.net)
