// CodeGear C++Builder
// Copyright (c) 1995, 2009 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'Tmsd2010.pas' rev: 21.00

#ifndef Tmsd2010HPP
#define Tmsd2010HPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member functions
#pragma pack(push,8)
#include <System.hpp>	// Pascal unit
#include <Sysinit.hpp>	// Pascal unit
#include <Asgreg.hpp>	// Pascal unit
#include <Asgcreg.hpp>	// Pascal unit
#include <Asghtml.hpp>	// Pascal unit
#include <Asgprev.hpp>	// Pascal unit
#include <Asgprint.hpp>	// Pascal unit
#include <Dbadvlst.hpp>	// Pascal unit
#include <Advgrid.hpp>	// Pascal unit
#include <Advcolumnsetter.hpp>	// Pascal unit
#include <Asgimport.hpp>	// Pascal unit
#include <Advlistv.hpp>	// Pascal unit
#include <Advobj.hpp>	// Pascal unit
#include <Advutil.hpp>	// Pascal unit
#include <Advcgrid.hpp>	// Pascal unit
#include <Alvreg.hpp>	// Pascal unit
#include <Alvutil.hpp>	// Pascal unit
#include <Planner.hpp>	// Pascal unit
#include <Planutil.hpp>	// Pascal unit
#include <Planreg.hpp>	// Pascal unit
#include <Slstbox.hpp>	// Pascal unit
#include <Slstreg.hpp>	// Pascal unit
#include <Advpnlreg.hpp>	// Pascal unit
#include <Advpanel.hpp>	// Pascal unit
#include <Advimage.hpp>	// Pascal unit
#include <Lucombo.hpp>	// Pascal unit
#include <Dblucmbr.hpp>	// Pascal unit
#include <Dblucomb.hpp>	// Pascal unit
#include <Asreg.hpp>	// Pascal unit
#include <Advspin.hpp>	// Pascal unit
#include <Advcombo.hpp>	// Pascal unit
#include <Advedit.hpp>	// Pascal unit
#include <Dbadvle.hpp>	// Pascal unit
#include <Advedbtn.hpp>	// Pascal unit
#include <Advlued.hpp>	// Pascal unit
#include <Advluedr.hpp>	// Pascal unit
#include <Advedbr.hpp>	// Pascal unit
#include <Dbadvler.hpp>	// Pascal unit
#include <Asgedit.hpp>	// Pascal unit
#include <Asgspin.hpp>	// Pascal unit
#include <Adveddd.hpp>	// Pascal unit
#include <Dbasreg.hpp>	// Pascal unit
#include <Dbaereg.hpp>	// Pascal unit
#include <Dbadved.hpp>	// Pascal unit
#include <Dbadvsp.hpp>	// Pascal unit
#include <Editbtn.hpp>	// Pascal unit
#include <Edtbreg.hpp>	// Pascal unit
#include <Moneyedit.hpp>	// Pascal unit
#include <Moneyedr.hpp>	// Pascal unit
#include <Dbmereg.hpp>	// Pascal unit
#include <Dbmnyed.hpp>	// Pascal unit
#include <Mskreg.hpp>	// Pascal unit
#include <Maskedex.hpp>	// Pascal unit
#include <Cabr.hpp>	// Pascal unit
#include <Cabfiles.hpp>	// Pascal unit
#include <Editlist.hpp>	// Pascal unit
#include <Llreg.hpp>	// Pascal unit
#include <Listlink.hpp>	// Pascal unit
#include <Hilireg.hpp>	// Pascal unit
#include <Hintlist.hpp>	// Pascal unit
#include <Wdatreg.hpp>	// Pascal unit
#include <Webdata.hpp>	// Pascal unit
#include <Webcreg.hpp>	// Pascal unit
#include <Webcopy.hpp>	// Pascal unit
#include <Wupdreg.hpp>	// Pascal unit
#include <Wupdate.hpp>	// Pascal unit
#include <Wupdatelanguagesu.hpp>	// Pascal unit
#include <Cabfdi.hpp>	// Pascal unit
#include <Webimage.hpp>	// Pascal unit
#include <Webimgr.hpp>	// Pascal unit
#include <Htmlireg.hpp>	// Pascal unit
#include <Htmhireg.hpp>	// Pascal unit
#include <Htmcoreg.hpp>	// Pascal unit
#include <Htmltvr.hpp>	// Pascal unit
#include <Htmlareg.hpp>	// Pascal unit
#include <Htmbureg.hpp>	// Pascal unit
#include <Htmcombo.hpp>	// Pascal unit
#include <Htmlabel.hpp>	// Pascal unit
#include <Htmlbtns.hpp>	// Pascal unit
#include <Htmlhint.hpp>	// Pascal unit
#include <Htmlistb.hpp>	// Pascal unit
#include <Htmltv.hpp>	// Pascal unit
#include <Htmstreg.hpp>	// Pascal unit
#include <Htmltext.hpp>	// Pascal unit
#include <Dbhtmlar.hpp>	// Pascal unit
#include <Dbhtmlab.hpp>	// Pascal unit
#include <Htmlstatusbar.hpp>	// Pascal unit
#include <Htmstbr.hpp>	// Pascal unit
#include <Colcoreg.hpp>	// Pascal unit
#include <Colcombo.hpp>	// Pascal unit
#include <Collistb.hpp>	// Pascal unit
#include <Collireg.hpp>	// Pascal unit
#include <Rtflreg.hpp>	// Pascal unit
#include <Rtflabel.hpp>	// Pascal unit
#include <Datelbl.hpp>	// Pascal unit
#include <Apreg.hpp>	// Pascal unit
#include <Clistedr.hpp>	// Pascal unit
#include <Clisted.hpp>	// Pascal unit
#include <Tlreg.hpp>	// Pascal unit
#include <Treelist.hpp>	// Pascal unit
#include <Paramlst.hpp>	// Pascal unit
#include <Paramlstreg.hpp>	// Pascal unit
#include <Paramchklreg.hpp>	// Pascal unit
#include <Paramlabel.hpp>	// Pascal unit
#include <Paramlabreg.hpp>	// Pascal unit
#include <Paramlistbox.hpp>	// Pascal unit
#include <Paramchklist.hpp>	// Pascal unit
#include <Anireg.hpp>	// Pascal unit
#include <Aniedit.hpp>	// Pascal unit
#include <Aniicon.hpp>	// Pascal unit
#include <Scrlreg.hpp>	// Pascal unit
#include <Propscrl.hpp>	// Pascal unit
#include <Advprogr.hpp>	// Pascal unit
#include <Seldlg.hpp>	// Pascal unit
#include <Wallpreg.hpp>	// Pascal unit
#include <Wallpaper.hpp>	// Pascal unit
#include <Pdlgreg.hpp>	// Pascal unit
#include <Pickdlg.hpp>	// Pascal unit
#include <Shelldlg.hpp>	// Pascal unit
#include <Ushldlg.hpp>	// Pascal unit
#include <Flctrlex.hpp>	// Pascal unit
#include <Flctrlr.hpp>	// Pascal unit
#include <Mswheel.hpp>	// Pascal unit
#include <Asgdd.hpp>	// Pascal unit
#include <Advpicture.hpp>	// Pascal unit
#include <Advpicr.hpp>	// Pascal unit
#include <Asgcombo.hpp>	// Pascal unit
#include <Webpost.hpp>	// Pascal unit
#include <Webpostr.hpp>	// Pascal unit
#include <Advquerydialog.hpp>	// Pascal unit
#include <Advqryr.hpp>	// Pascal unit
#include <Htmldlgr.hpp>	// Pascal unit
#include <Htmldialog.hpp>	// Pascal unit
#include <Dbplanreg.hpp>	// Pascal unit
#include <Dbplanner.hpp>	// Pascal unit
#include <Edtlstreg.hpp>	// Pascal unit
#include <Thumbreg.hpp>	// Pascal unit
#include <Thumbnaillist.hpp>	// Pascal unit
#include <Plannercalreg.hpp>	// Pascal unit
#include <Plannercal.hpp>	// Pascal unit
#include <Dbplannercalreg.hpp>	// Pascal unit
#include <Dbplannercal.hpp>	// Pascal unit
#include <Picturecontainerreg.hpp>	// Pascal unit
#include <Picturecontainer.hpp>	// Pascal unit
#include <Asgfinddialog.hpp>	// Pascal unit
#include <Acreg.hpp>	// Pascal unit
#include <Aereg.hpp>	// Pascal unit
#include <Lureg.hpp>	// Pascal unit
#include <Parlreg.hpp>	// Pascal unit
#include <Shader.hpp>	// Pascal unit
#include <Asgcheck.hpp>	// Pascal unit
#include <Dbplannerdatepicker.hpp>	// Pascal unit
#include <Plancheck.hpp>	// Pascal unit
#include <Plannerdatepicker.hpp>	// Pascal unit
#include <Paramtreeviewreg.hpp>	// Pascal unit
#include <Paramtreeview.hpp>	// Pascal unit
#include <Dbslstreg.hpp>	// Pascal unit
#include <Dbslstbox.hpp>	// Pascal unit
#include <Wucrc32.hpp>	// Pascal unit
#include <Astapatchutil.hpp>	// Pascal unit
#include <Dbtodolistreg.hpp>	// Pascal unit
#include <Dbtodolist.hpp>	// Pascal unit
#include <Todolistreg.hpp>	// Pascal unit
#include <Todolist.hpp>	// Pascal unit
#include <Winxp.hpp>	// Pascal unit
#include <Dbadvedbtnreg.hpp>	// Pascal unit
#include <Dbadvedbtn.hpp>	// Pascal unit
#include <Basegrid.hpp>	// Pascal unit
#include <Advxpvs.hpp>	// Pascal unit
#include <Btnxpvs.hpp>	// Pascal unit
#include <Htmlxpvs.hpp>	// Pascal unit
#include <Htmlpopupreg.hpp>	// Pascal unit
#include <Htmlpopup.hpp>	// Pascal unit
#include <Planxpvs.hpp>	// Pascal unit
#include <Planhtml.hpp>	// Pascal unit
#include <Plancombo.hpp>	// Pascal unit
#include <Asglinks.hpp>	// Pascal unit
#include <Inspxpvs.hpp>	// Pascal unit
#include <Iniinspectorbarreg.hpp>	// Pascal unit
#include <Inspdd.hpp>	// Pascal unit
#include <Inspectorbar.hpp>	// Pascal unit
#include <Inspectorbarreg.hpp>	// Pascal unit
#include <Inspedits.hpp>	// Pascal unit
#include <Inspimg.hpp>	// Pascal unit
#include <Iniinspectorbar.hpp>	// Pascal unit
#include <Dbinspectorbarreg.hpp>	// Pascal unit
#include <Dbinspectorbar.hpp>	// Pascal unit
#include <Rttiinspectorbarreg.hpp>	// Pascal unit
#include <Rttiinspectorbar.hpp>	// Pascal unit
#include <Btnlistb.hpp>	// Pascal unit
#include <Btnlireg.hpp>	// Pascal unit
#include <Colorcombo.hpp>	// Pascal unit
#include <Imagepicker.hpp>	// Pascal unit
#include <Atbreg.hpp>	// Pascal unit
#include <Dbanreg.hpp>	// Pascal unit
#include <Aebxpvs.hpp>	// Pascal unit
#include <Apxpvs.hpp>	// Pascal unit
#include <Advdirectoryedit.hpp>	// Pascal unit
#include <Advfilenameedit.hpp>	// Pascal unit
#include <Advtoolbtn.hpp>	// Pascal unit
#include <Dbadvnavigator.hpp>	// Pascal unit
#include <Ccedlink.hpp>	// Pascal unit
#include <Dbhtmlbtnsreg.hpp>	// Pascal unit
#include <Dbhtmlbtns.hpp>	// Pascal unit
#include <Webconnect.hpp>	// Pascal unit
#include <Webconnectreg.hpp>	// Pascal unit
#include <Asghtmle.hpp>	// Pascal unit
#include <Asgmemo.hpp>	// Pascal unit
#include <Planperiodedit.hpp>	// Pascal unit
#include <Planitemedit.hpp>	// Pascal unit
#include <Plandraw.hpp>	// Pascal unit
#include <Plansimpleedit.hpp>	// Pascal unit
#include <Advmps.hpp>	// Pascal unit
#include <Advmemo.hpp>	// Pascal unit
#include <Advmemoreg.hpp>	// Pascal unit
#include <Advmcss.hpp>	// Pascal unit
#include <Advshaper.hpp>	// Pascal unit
#include <Advshaperreg.hpp>	// Pascal unit
#include <Asxpvs.hpp>	// Pascal unit
#include <Acxpvs.hpp>	// Pascal unit
#include <Advmoneyedit.hpp>	// Pascal unit
#include <Dbadvmoneyedit.hpp>	// Pascal unit
#include <Advmoneyeditreg.hpp>	// Pascal unit
#include <Insplinks.hpp>	// Pascal unit
#include <Wuwizform.hpp>	// Pascal unit
#include <Wupdatewiz.hpp>	// Pascal unit
#include <Asgreplacedialog.hpp>	// Pascal unit
#include <Advdblookupcomboboxreg.hpp>	// Pascal unit
#include <Advdblookupcombobox.hpp>	// Pascal unit
#include <Planproppref.hpp>	// Pascal unit
#include <Advmbs.hpp>	// Pascal unit
#include <Gradientlblreg.hpp>	// Pascal unit
#include <Gradientlabel.hpp>	// Pascal unit
#include <Htmltreelist.hpp>	// Pascal unit
#include <Htmltlreg.hpp>	// Pascal unit
#include <Dbadvmemo.hpp>	// Pascal unit
#include <Advmsqls.hpp>	// Pascal unit
#include <Advtreecomboboxreg.hpp>	// Pascal unit
#include <Advtreecombobox.hpp>	// Pascal unit
#include <Htmlcreditreg.hpp>	// Pascal unit
#include <Htmlcredit.hpp>	// Pascal unit
#include <Parhtml.hpp>	// Pascal unit
#include <Parxpvs.hpp>	// Pascal unit
#include <Advmws.hpp>	// Pascal unit
#include <Frmctrllink.hpp>	// Pascal unit
#include <Vcalreg.hpp>	// Pascal unit
#include <Vcal.hpp>	// Pascal unit
#include <Toolpanelsreg.hpp>	// Pascal unit
#include <Toolpanels.hpp>	// Pascal unit
#include <Advmcshs.hpp>	// Pascal unit
#include <Advmes.hpp>	// Pascal unit
#include <Advmpls.hpp>	// Pascal unit
#include <Advmpys.hpp>	// Pascal unit
#include <Advprogressbarreg.hpp>	// Pascal unit
#include <Advprogressbar.hpp>	// Pascal unit
#include <Advgradient.hpp>	// Pascal unit
#include <Advgridworkbook.hpp>	// Pascal unit
#include <Plannerwaitlist.hpp>	// Pascal unit
#include <Planstyles.hpp>	// Pascal unit
#include <Plannermaskdatepicker.hpp>	// Pascal unit
#include <Advpagecontrol.hpp>	// Pascal unit
#include <Advpagecontrolreg.hpp>	// Pascal unit
#include <Advmedbtn.hpp>	// Pascal unit
#include <Planobj.hpp>	// Pascal unit
#include <Advtabset.hpp>	// Pascal unit
#include <Advtabsetreg.hpp>	// Pascal unit
#include <Htmlchklireg.hpp>	// Pascal unit
#include <Htmlchklist.hpp>	// Pascal unit
#include <Advcodelistlib.hpp>	// Pascal unit
#include <Advcodelist.hpp>	// Pascal unit
#include <Advcodelistdd.hpp>	// Pascal unit
#include <Advcodehint.hpp>	// Pascal unit
#include <Advalertwindowreg.hpp>	// Pascal unit
#include <Advalertwindow.hpp>	// Pascal unit
#include <Advnavbarreg.hpp>	// Pascal unit
#include <Advnavbar.hpp>	// Pascal unit
#include <Dbplannermonthviewreg.hpp>	// Pascal unit
#include <Dbplannermonthview.hpp>	// Pascal unit
#include <Plannermonthviewreg.hpp>	// Pascal unit
#include <Plannermonthview.hpp>	// Pascal unit
#include <Todoxpvs.hpp>	// Pascal unit
#include <Wulogin.hpp>	// Pascal unit
#include <Wubase64.hpp>	// Pascal unit
#include <Advmemostylermanager.hpp>	// Pascal unit
#include <Advminis.hpp>	// Pascal unit
#include <Advmxml.hpp>	// Pascal unit
#include <Planrecurredit.hpp>	// Pascal unit
#include <Planrecurr.hpp>	// Pascal unit
#include <Imgpickr.hpp>	// Pascal unit
#include <Advfontcombo.hpp>	// Pascal unit
#include <Advselectors.hpp>	// Pascal unit
#include <Tmsgraphicsreg.hpp>	// Pascal unit
#include <Advmenuutil.hpp>	// Pascal unit
#include <Advmenus.hpp>	// Pascal unit
#include <Advmenustylers.hpp>	// Pascal unit
#include <Advmenuregister.hpp>	// Pascal unit
#include <Plannerdbmaskdatepicker.hpp>	// Pascal unit
#include <Plannerdbdatepicker.hpp>	// Pascal unit
#include <Dbadvgridreg.hpp>	// Pascal unit
#include <Dbadvgrid.hpp>	// Pascal unit
#include <Atxpvs.hpp>	// Pascal unit
#include <Wcbase64.hpp>	// Pascal unit
#include <Wclogin.hpp>	// Pascal unit
#include <Tilebmp.hpp>	// Pascal unit
#include <Advcardliststyler.hpp>	// Pascal unit
#include <Advcardlist.hpp>	// Pascal unit
#include <Acldd.hpp>	// Pascal unit
#include <Advcardlistgradient.hpp>	// Pascal unit
#include <Advcardlistreg.hpp>	// Pascal unit
#include <Dbadvcardlistreg.hpp>	// Pascal unit
#include <Dbadvcardlist.hpp>	// Pascal unit
#include <Advtoolbarstylers.hpp>	// Pascal unit
#include <Advtoolbar.hpp>	// Pascal unit
#include <Advtoolbarreg.hpp>	// Pascal unit
#include <Picturelist.hpp>	// Pascal unit
#include <Piclistreg.hpp>	// Pascal unit
#include <Alxpvs.hpp>	// Pascal unit
#include <Cexpvs.hpp>	// Pascal unit
#include <Rtfengine.hpp>	// Pascal unit
#include <Advgridcsvpager.hpp>	// Pascal unit
#include <Advoutlooklistreg.hpp>	// Pascal unit
#include <Advoutlooklist.hpp>	// Pascal unit
#include <Outlookgroupedlist.hpp>	// Pascal unit
#include <Customizeru.hpp>	// Pascal unit
#include <Customizerbtnu.hpp>	// Pascal unit
#include <Planneractions.hpp>	// Pascal unit
#include <Advmphp.hpp>	// Pascal unit
#include <Gdipicture.hpp>	// Pascal unit
#include <Advgdip.hpp>	// Pascal unit
#include <Advglowbutton.hpp>	// Pascal unit
#include <Advglowbuttonreg.hpp>	// Pascal unit
#include <Advgridrtf.hpp>	// Pascal unit
#include <Advofficehintreg.hpp>	// Pascal unit
#include <Advofficehint.hpp>	// Pascal unit
#include <Advhintinfo.hpp>	// Pascal unit
#include <Advstyleif.hpp>	// Pascal unit
#include <Advappstyler.hpp>	// Pascal unit
#include <Advofficepagerstylers.hpp>	// Pascal unit
#include <Advofficepager.hpp>	// Pascal unit
#include <Advofficepagerreg.hpp>	// Pascal unit
#include <Advofficetabsetstylers.hpp>	// Pascal unit
#include <Advofficestatusbar.hpp>	// Pascal unit
#include <Advofficestatusbarreg.hpp>	// Pascal unit
#include <Advofficestatusbarstylers.hpp>	// Pascal unit
#include <Advofficetabset.hpp>	// Pascal unit
#include <Advofficetabsetreg.hpp>	// Pascal unit
#include <Tmsofficegraphicsreg.hpp>	// Pascal unit
#include <Advofficeselectors.hpp>	// Pascal unit
#include <Advofficecombobox.hpp>	// Pascal unit
#include <Advofficeimage.hpp>	// Pascal unit
#include <Advofficeimagereg.hpp>	// Pascal unit
#include <Advshapebutton.hpp>	// Pascal unit
#include <Advshapebuttonreg.hpp>	// Pascal unit
#include <Advpreviewmenustylers.hpp>	// Pascal unit
#include <Advpreviewmenu.hpp>	// Pascal unit
#include <Advpreviewmenureg.hpp>	// Pascal unit
#include <Taskdialog.hpp>	// Pascal unit
#include <Taskdialogex.hpp>	// Pascal unit
#include <Htmlform.hpp>	// Pascal unit
#include <Htmlformreg.hpp>	// Pascal unit
#include <Folderdialog.hpp>	// Pascal unit
#include <Folderdialogreg.hpp>	// Pascal unit
#include <Advsplitter.hpp>	// Pascal unit
#include <Advsplitterreg.hpp>	// Pascal unit
#include <Advwiiprogressbar.hpp>	// Pascal unit
#include <Advwiiprogressbarreg.hpp>	// Pascal unit
#include <Advgroupbox.hpp>	// Pascal unit
#include <Advgroupboxreg.hpp>	// Pascal unit
#include <Advofficebuttons.hpp>	// Pascal unit
#include <Aobxpvs.hpp>	// Pascal unit
#include <Dbadvtrackbar.hpp>	// Pascal unit
#include <Dbadvtrackbarreg.hpp>	// Pascal unit
#include <Advofficebuttonsreg.hpp>	// Pascal unit
#include <Advscrollbox.hpp>	// Pascal unit
#include <Advscrollboxreg.hpp>	// Pascal unit
#include <Dbadvmoneyeditreg.hpp>	// Pascal unit
#include <Advreflectionimage.hpp>	// Pascal unit
#include <Advreflectionimagereg.hpp>	// Pascal unit
#include <Advreflectionlabel.hpp>	// Pascal unit
#include <Advreflabelreg.hpp>	// Pascal unit
#include <Advglassbutton.hpp>	// Pascal unit
#include <Advglassbuttonreg.hpp>	// Pascal unit
#include <Dbadvofficebuttons.hpp>	// Pascal unit
#include <Dbadvofficebuttonsreg.hpp>	// Pascal unit
#include <Advtrackbar.hpp>	// Pascal unit
#include <Advtrackbarreg.hpp>	// Pascal unit
#include <Advshape.hpp>	// Pascal unit
#include <Advshapereg.hpp>	// Pascal unit
#include <Advsmartmessagebox.hpp>	// Pascal unit
#include <Advsmartmessageboxreg.hpp>	// Pascal unit
#include <Atbxpvs.hpp>	// Pascal unit
#include <Advstickypopupmenu.hpp>	// Pascal unit
#include <Advstickypopupmenureg.hpp>	// Pascal unit
#include <Advdatetimepicker.hpp>	// Pascal unit
#include <Advdbdatetimepicker.hpp>	// Pascal unit
#include <Advdatetimepickerreg.hpp>	// Pascal unit
#include <Dbadvglownavigatorreg.hpp>	// Pascal unit
#include <Dbadvglownavigator.hpp>	// Pascal unit
#include <Advcircularprogress.hpp>	// Pascal unit
#include <Advcircularprogressreg.hpp>	// Pascal unit
#include <Wheelreg.hpp>	// Pascal unit
#include <Advcalculatordropdown.hpp>	// Pascal unit
#include <Advdropdown.hpp>	// Pascal unit
#include <Advcolorpickerdropdown.hpp>	// Pascal unit
#include <Advcontroldropdown.hpp>	// Pascal unit
#include <Advdetaildropdown.hpp>	// Pascal unit
#include <Advdropdownreg.hpp>	// Pascal unit
#include <Advimagepickerdropdown.hpp>	// Pascal unit
#include <Advmemodropdown.hpp>	// Pascal unit
#include <Advmulticolumndropdown.hpp>	// Pascal unit
#include <Advtimepickerdropdown.hpp>	// Pascal unit
#include <Advtrackbardropdown.hpp>	// Pascal unit
#include <Dbadvmemodropdown.hpp>	// Pascal unit
#include <Dbadvcontroldropdown.hpp>	// Pascal unit
#include <Dbadvdetaildropdown.hpp>	// Pascal unit
#include <Dbadvmulticolumndropdown.hpp>	// Pascal unit
#include <Dbadvtimepickerdropdown.hpp>	// Pascal unit
#include <Dbadvimagepickerdropdown.hpp>	// Pascal unit
#include <Dbadvcolorpickerdropdown.hpp>	// Pascal unit
#include <Dbadvcalculatordropdown.hpp>	// Pascal unit
#include <Dbadvtrackbardropdown.hpp>	// Pascal unit
#include <Dbadvdropdownreg.hpp>	// Pascal unit
#include <Advtbxpvs.hpp>	// Pascal unit
#include <Advdwm.hpp>	// Pascal unit
#include <Dbadvpicturereg.hpp>	// Pascal unit
#include <Advdbcombobox.hpp>	// Pascal unit
#include <Advdbcomboboxreg.hpp>	// Pascal unit
#include <Advgriddropdown.hpp>	// Pascal unit
#include <Advgriddropdownreg.hpp>	// Pascal unit
#include <Advcustomgriddropdown.hpp>	// Pascal unit
#include <Dbadvpicture.hpp>	// Pascal unit
#include <Variants.hpp>	// Pascal unit
#include <Windows.hpp>	// Pascal unit
#include <Sysutils.hpp>	// Pascal unit
#include <Varutils.hpp>	// Pascal unit
#include <Typinfo.hpp>	// Pascal unit
#include <Classes.hpp>	// Pascal unit
#include <Ioutils.hpp>	// Pascal unit
#include <Inifiles.hpp>	// Pascal unit
#include <Registry.hpp>	// Pascal unit
#include <Graphics.hpp>	// Pascal unit
#include <Multimon.hpp>	// Pascal unit
#include <Actnlist.hpp>	// Pascal unit
#include <Helpintfs.hpp>	// Pascal unit
#include <Timespan.hpp>	// Pascal unit
#include <Syncobjs.hpp>	// Pascal unit
#include <Uxtheme.hpp>	// Pascal unit
#include <Flatsb.hpp>	// Pascal unit
#include <Printers.hpp>	// Pascal unit
#include <Themes.hpp>	// Pascal unit
#include <Graphutil.hpp>	// Pascal unit
#include <Extctrls.hpp>	// Pascal unit
#include <Comctrls.hpp>	// Pascal unit
#include <Dialogs.hpp>	// Pascal unit
#include <Clipbrd.hpp>	// Pascal unit
#include <Forms.hpp>	// Pascal unit
#include <Menus.hpp>	// Pascal unit
#include <Controls.hpp>	// Pascal unit
#include <Buttons.hpp>	// Pascal unit
#include <Comobj.hpp>	// Pascal unit
#include <Olectnrs.hpp>	// Pascal unit
#include <Jpeg.hpp>	// Pascal unit
#include <Tabs.hpp>	// Pascal unit
#include <Sqltimst.hpp>	// Pascal unit
#include <Fmtbcd.hpp>	// Pascal unit
#include <Widestrings.hpp>	// Pascal unit
#include <Db.hpp>	// Pascal unit
#include <Dblogdlg.hpp>	// Pascal unit
#include <Dbpwdlg.hpp>	// Pascal unit
#include <Dbctrls.hpp>	// Pascal unit
#include <Extdlgs.hpp>	// Pascal unit
#include <Checklst.hpp>	// Pascal unit
#include <Appevnts.hpp>	// Pascal unit
#include <Axctrls.hpp>	// Pascal unit
#include <Mapi.hpp>	// Pascal unit
#include <Extactns.hpp>	// Pascal unit
#include <Actnmenus.hpp>	// Pascal unit
#include <Actnman.hpp>	// Pascal unit
#include <Dbtables.hpp>	// Pascal unit

//-- user supplied -----------------------------------------------------------

namespace Tmsd2010
{
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------

}	/* namespace Tmsd2010 */
using namespace Tmsd2010;
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Tmsd2010HPP
