// CodeGear C++Builder
// Copyright (c) 1995, 2009 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'Tmsded2010.pas' rev: 21.00

#ifndef Tmsded2010HPP
#define Tmsded2010HPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member functions
#pragma pack(push,8)
#include <System.hpp>	// Pascal unit
#include <Sysinit.hpp>	// Pascal unit
#include <Acgde.hpp>	// Pascal unit
#include <Advdblookupcomboboxregde.hpp>	// Pascal unit
#include <Advdblookupcomboboxde.hpp>	// Pascal unit
#include <Advimgde.hpp>	// Pascal unit
#include <Advmemoregde.hpp>	// Pascal unit
#include <Advmemode.hpp>	// Pascal unit
#include <Advmemoac.hpp>	// Pascal unit
#include <Advpagecontrolregde.hpp>	// Pascal unit
#include <Advpagecontrolde.hpp>	// Pascal unit
#include <Advpicde.hpp>	// Pascal unit
#include <Advpicregde.hpp>	// Pascal unit
#include <Advpnlde.hpp>	// Pascal unit
#include <Advpnlregde.hpp>	// Pascal unit
#include <Advtoolbuttonstyles.hpp>	// Pascal unit
#include <Advtoolbuttonde.hpp>	// Pascal unit
#include <Advtreecomboboxregde.hpp>	// Pascal unit
#include <Advtreecomboboxde.hpp>	// Pascal unit
#include <Alvregde.hpp>	// Pascal unit
#include <Alvde.hpp>	// Pascal unit
#include <Anide.hpp>	// Pascal unit
#include <Aniregde.hpp>	// Pascal unit
#include <Asgde.hpp>	// Pascal unit
#include <Asgcregde.hpp>	// Pascal unit
#include <Asgregde.hpp>	// Pascal unit
#include <Asgproppref.hpp>	// Pascal unit
#include <Atbregde.hpp>	// Pascal unit
#include <Cabregde.hpp>	// Pascal unit
#include <Calcregde.hpp>	// Pascal unit
#include <Colordlg.hpp>	// Pascal unit
#include <Dbalvde.hpp>	// Pascal unit
#include <Dbhtmlaregde.hpp>	// Pascal unit
#include <Dbhtmlbtnsregde.hpp>	// Pascal unit
#include <Dbinspde.hpp>	// Pascal unit
#include <Dbinspectorbarregde.hpp>	// Pascal unit
#include <Dbplande.hpp>	// Pascal unit
#include <Dbplannercalregde.hpp>	// Pascal unit
#include <Dbplannercalde.hpp>	// Pascal unit
#include <Dbplanregde.hpp>	// Pascal unit
#include <Dbtodolistregde.hpp>	// Pascal unit
#include <Dbtodolistde.hpp>	// Pascal unit
#include <Frtfbox.hpp>	// Pascal unit
#include <Hotspotimageregde.hpp>	// Pascal unit
#include <Hotspoteditorde.hpp>	// Pascal unit
#include <Htmlaregde.hpp>	// Pascal unit
#include <Htmburegde.hpp>	// Pascal unit
#include <Htmlcreditregde.hpp>	// Pascal unit
#include <Htmlchkliregde.hpp>	// Pascal unit
#include <Htmlde.hpp>	// Pascal unit
#include <Htmlpopupregde.hpp>	// Pascal unit
#include <Htmlsde.hpp>	// Pascal unit
#include <Htmstregde.hpp>	// Pascal unit
#include <Inspectorbarregde.hpp>	// Pascal unit
#include <Inspde.hpp>	// Pascal unit
#include <Paramchklregde.hpp>	// Pascal unit
#include <Paramtreeviewregde.hpp>	// Pascal unit
#include <Paramlstregde.hpp>	// Pascal unit
#include <Paramlabregde.hpp>	// Pascal unit
#include <Paramde.hpp>	// Pascal unit
#include <Paramedit.hpp>	// Pascal unit
#include <Paramsde.hpp>	// Pascal unit
#include <Parlregde.hpp>	// Pascal unit
#include <Pdlgregde.hpp>	// Pascal unit
#include <Picturecontainerde.hpp>	// Pascal unit
#include <Picturecontainerregde.hpp>	// Pascal unit
#include <Plande.hpp>	// Pascal unit
#include <Plannercalregde.hpp>	// Pascal unit
#include <Planregde.hpp>	// Pascal unit
#include <Rtflregde.hpp>	// Pascal unit
#include <Rtflde.hpp>	// Pascal unit
#include <Slstregde.hpp>	// Pascal unit
#include <Slstde.hpp>	// Pascal unit
#include <Thumbregde.hpp>	// Pascal unit
#include <Thumbde.hpp>	// Pascal unit
#include <Toolpanelsregde.hpp>	// Pascal unit
#include <Toolpanelsde.hpp>	// Pascal unit
#include <Htmlformregde.hpp>	// Pascal unit
#include <Wallpde.hpp>	// Pascal unit
#include <Wallpregde.hpp>	// Pascal unit
#include <Webimgregde.hpp>	// Pascal unit
#include <Webimgde.hpp>	// Pascal unit
#include <Paramtreeprop.hpp>	// Pascal unit
#include <Paramprop.hpp>	// Pascal unit
#include <Paramlistprop.hpp>	// Pascal unit
#include <Picturecontainerprop.hpp>	// Pascal unit
#include <Umemoedit.hpp>	// Pascal unit
#include <Htmlprop.hpp>	// Pascal unit
#include <Advnavbarregde.hpp>	// Pascal unit
#include <Advalertwindowregde.hpp>	// Pascal unit
#include <Dbplannermonthviewregde.hpp>	// Pascal unit
#include <Plannermonthviewregde.hpp>	// Pascal unit
#include <Advhtmlde.hpp>	// Pascal unit
#include <Advalertmessagede.hpp>	// Pascal unit
#include <Advhtmlprop.hpp>	// Pascal unit
#include <Todolistregde.hpp>	// Pascal unit
#include <Todolistde.hpp>	// Pascal unit
#include <Dbadvgridde.hpp>	// Pascal unit
#include <Advcardlistregde.hpp>	// Pascal unit
#include <Dbadvcardlistregde.hpp>	// Pascal unit
#include <Advtoolbarregde.hpp>	// Pascal unit
#include <Advtoolbarde.hpp>	// Pascal unit
#include <Asggallery.hpp>	// Pascal unit
#include <Tmssplash.hpp>	// Pascal unit
#include <Advoutlooklistde.hpp>	// Pascal unit
#include <Advglowbuttonregde.hpp>	// Pascal unit
#include <Gdipicde.hpp>	// Pascal unit
#include <Advofficehintregde.hpp>	// Pascal unit
#include <Advofficepagerde.hpp>	// Pascal unit
#include <Advofficepagerregde.hpp>	// Pascal unit
#include <Advofficetabsetregde.hpp>	// Pascal unit
#include <Advofficeselectorsregde.hpp>	// Pascal unit
#include <Advofficecomboboxregde.hpp>	// Pascal unit
#include <Advofficeimageregde.hpp>	// Pascal unit
#include <Advshapebuttonregde.hpp>	// Pascal unit
#include <Advpreviewmenuregde.hpp>	// Pascal unit
#include <Advpreviewmenude.hpp>	// Pascal unit
#include <Advpreviewmenueditor.hpp>	// Pascal unit
#include <Taskdialogde.hpp>	// Pascal unit
#include <Taskdialogregde.hpp>	// Pascal unit
#include <Advreflectionimageregde.hpp>	// Pascal unit
#include <Advreflabelregde.hpp>	// Pascal unit
#include <Advglassbuttonregde.hpp>	// Pascal unit
#include <Advtrackbarregde.hpp>	// Pascal unit
#include <Advtrackbargallery.hpp>	// Pascal unit
#include <Advrangeslidergallery.hpp>	// Pascal unit
#include <Advtrackbarpersist.hpp>	// Pascal unit
#include <Advshaperegde.hpp>	// Pascal unit
#include <Advsmartmessageboxregde.hpp>	// Pascal unit
#include <Advstickypopupmenude.hpp>	// Pascal unit
#include <Advstickypopupmenuregde.hpp>	// Pascal unit
#include <Advgdipde.hpp>	// Pascal unit
#include <Advgdipregde.hpp>	// Pascal unit
#include <Advsmoothbuttonregde.hpp>	// Pascal unit
#include <Advsmoothbuttonde.hpp>	// Pascal unit
#include <Advsmoothcalendarde.hpp>	// Pascal unit
#include <Advsmoothcalendarregde.hpp>	// Pascal unit
#include <Advsmoothdatepickerde.hpp>	// Pascal unit
#include <Advsmoothdatepickerregde.hpp>	// Pascal unit
#include <Advsmoothlistboxde.hpp>	// Pascal unit
#include <Advsmoothlistboxregde.hpp>	// Pascal unit
#include <Advsmoothimagelistboxde.hpp>	// Pascal unit
#include <Advsmoothimagelistboxregde.hpp>	// Pascal unit
#include <Advsmoothimagelistboxpickerde.hpp>	// Pascal unit
#include <Advsmoothimagelistboxpickerregde.hpp>	// Pascal unit
#include <Advsmoothpanelde.hpp>	// Pascal unit
#include <Advsmoothpanelregde.hpp>	// Pascal unit
#include <Advsmoothmenude.hpp>	// Pascal unit
#include <Advsmoothmenuregde.hpp>	// Pascal unit
#include <Advsmoothhtmlprop.hpp>	// Pascal unit
#include <Advsmoothspinnerde.hpp>	// Pascal unit
#include <Advsmoothspinnerregde.hpp>	// Pascal unit
#include <Advsmoothtogglebuttonde.hpp>	// Pascal unit
#include <Advsmoothtogglebuttonregde.hpp>	// Pascal unit
#include <Advsmoothtrackbarde.hpp>	// Pascal unit
#include <Advsmoothtrackbarregde.hpp>	// Pascal unit
#include <Advsmoothtabpagerde.hpp>	// Pascal unit
#include <Advsmoothtabpagerregde.hpp>	// Pascal unit
#include <Advsmoothgaugede.hpp>	// Pascal unit
#include <Advsmoothgaugeregde.hpp>	// Pascal unit
#include <Advsmoothprogressbarde.hpp>	// Pascal unit
#include <Advsmoothprogressbarregde.hpp>	// Pascal unit
#include <Advsmoothsliderde.hpp>	// Pascal unit
#include <Advsmoothsliderregde.hpp>	// Pascal unit
#include <Advsmoothscrollbarde.hpp>	// Pascal unit
#include <Advsmoothscrollbarregde.hpp>	// Pascal unit
#include <Advsmoothdockde.hpp>	// Pascal unit
#include <Advsmoothdockregde.hpp>	// Pascal unit
#include <Advsmoothexpanderpanelde.hpp>	// Pascal unit
#include <Advsmoothexpanderpanelregde.hpp>	// Pascal unit
#include <Advsmoothexpanderbuttonpanelde.hpp>	// Pascal unit
#include <Advsmoothexpanderbuttonpanelregde.hpp>	// Pascal unit
#include <Advsmoothexpandergroupde.hpp>	// Pascal unit
#include <Advsmoothexpandergroupregde.hpp>	// Pascal unit
#include <Advsmoothmessagedialogde.hpp>	// Pascal unit
#include <Advsmoothmessagedialogregde.hpp>	// Pascal unit
#include <Advsmoothsplashscreende.hpp>	// Pascal unit
#include <Advsmoothsplashscreenregde.hpp>	// Pascal unit
#include <Advsmoothtimelinede.hpp>	// Pascal unit
#include <Advsmoothtimelineregde.hpp>	// Pascal unit
#include <Advsmoothcalculatorde.hpp>	// Pascal unit
#include <Advsmoothcalculatorregde.hpp>	// Pascal unit
#include <Advsmoothmegamenuregde.hpp>	// Pascal unit
#include <Advsmoothmegamenude.hpp>	// Pascal unit
#include <Advsmoothmegamenueditor.hpp>	// Pascal unit
#include <Advsmoothmegamenugallery.hpp>	// Pascal unit
#include <Advexplorertreeviewde.hpp>	// Pascal unit
#include <Advexplorertreeviewregde.hpp>	// Pascal unit
#include <Advexplorertreeviewstyles.hpp>	// Pascal unit
#include <Advexplorertreevieweditor.hpp>	// Pascal unit
#include <Advdropdownde.hpp>	// Pascal unit
#include <Advdropdownregde.hpp>	// Pascal unit
#include <Advdropdownstyles.hpp>	// Pascal unit
#include <Advgdipicde.hpp>	// Pascal unit
#include <Advgdipicregde.hpp>	// Pascal unit
#include <Gdipfillregde.hpp>	// Pascal unit
#include <Gdipfillde.hpp>	// Pascal unit
#include <Gdipmenude.hpp>	// Pascal unit
#include <Gdipmenuregde.hpp>	// Pascal unit
#include <Dbadvglownavigatorde.hpp>	// Pascal unit
#include <Dbadvsmoothtimelineregde.hpp>	// Pascal unit
#include <Advdbcomboboxde.hpp>	// Pascal unit
#include <Advdbcomboboxlisteditor.hpp>	// Pascal unit
#include <Advdbcomboboxregde.hpp>	// Pascal unit
#include <Dbadvsmoothcomboboxde.hpp>	// Pascal unit
#include <Dbadvsmoothcomboboxregde.hpp>	// Pascal unit
#include <Dbadvsmoothimagelistboxde.hpp>	// Pascal unit
#include <Dbadvsmoothimagelistboxregde.hpp>	// Pascal unit
#include <Dbadvsmoothlistboxde.hpp>	// Pascal unit
#include <Dbadvsmoothlistboxregde.hpp>	// Pascal unit
#include <Dbadvsmoothdatepickerde.hpp>	// Pascal unit
#include <Dbadvsmoothdatepickerregde.hpp>	// Pascal unit
#include <Dbadvsmoothtimelinede.hpp>	// Pascal unit
#include <Advstyles.hpp>	// Pascal unit
#include <Advpolypagerde.hpp>	// Pascal unit
#include <Advpolypagerregde.hpp>	// Pascal unit
#include <Gdipcustomitemde.hpp>	// Pascal unit
#include <Gdipcustomitemregde.hpp>	// Pascal unit
#include <Customeditor.hpp>	// Pascal unit
#include <Customeditorde.hpp>	// Pascal unit
#include <Customeditorregde.hpp>	// Pascal unit
#include <Customitemscontainerde.hpp>	// Pascal unit
#include <Customitemscontainerregde.hpp>	// Pascal unit
#include <Advsmoothslideshowregde.hpp>	// Pascal unit
#include <Advsmoothslideshowde.hpp>	// Pascal unit
#include <Advshapebuttonde.hpp>	// Pascal unit
#include <Advsmoothcapacitybarde.hpp>	// Pascal unit
#include <Advsmoothcapacitybarregde.hpp>	// Pascal unit
#include <Gdippicturecontainerregde.hpp>	// Pascal unit
#include <Gdippicturecontainerde.hpp>	// Pascal unit
#include <Gdippicturecontainereditor.hpp>	// Pascal unit
#include <Variants.hpp>	// Pascal unit
#include <Windows.hpp>	// Pascal unit
#include <Sysutils.hpp>	// Pascal unit
#include <Varutils.hpp>	// Pascal unit
#include <Typinfo.hpp>	// Pascal unit
#include <Classes.hpp>	// Pascal unit
#include <Ioutils.hpp>	// Pascal unit
#include <Inifiles.hpp>	// Pascal unit
#include <Registry.hpp>	// Pascal unit
#include <Graphics.hpp>	// Pascal unit
#include <Multimon.hpp>	// Pascal unit
#include <Actnlist.hpp>	// Pascal unit
#include <Helpintfs.hpp>	// Pascal unit
#include <Timespan.hpp>	// Pascal unit
#include <Syncobjs.hpp>	// Pascal unit
#include <Uxtheme.hpp>	// Pascal unit
#include <Flatsb.hpp>	// Pascal unit
#include <Printers.hpp>	// Pascal unit
#include <Themes.hpp>	// Pascal unit
#include <Graphutil.hpp>	// Pascal unit
#include <Extctrls.hpp>	// Pascal unit
#include <Comctrls.hpp>	// Pascal unit
#include <Dialogs.hpp>	// Pascal unit
#include <Clipbrd.hpp>	// Pascal unit
#include <Forms.hpp>	// Pascal unit
#include <Menus.hpp>	// Pascal unit
#include <Controls.hpp>	// Pascal unit
#include <Buttons.hpp>	// Pascal unit
#include <Comobj.hpp>	// Pascal unit
#include <Advgdip.hpp>	// Pascal unit
#include <Advxpvs.hpp>	// Pascal unit
#include <Asghtmle.hpp>	// Pascal unit
#include <Olectnrs.hpp>	// Pascal unit
#include <Jpeg.hpp>	// Pascal unit
#include <Asgdd.hpp>	// Pascal unit
#include <Advdatetimepicker.hpp>	// Pascal unit
#include <Atxpvs.hpp>	// Pascal unit
#include <Advgrid.hpp>	// Pascal unit
#include <Advcgrid.hpp>	// Pascal unit
#include <Idemessages.hpp>	// Pascal unit
#include <Captioneddocktree.hpp>	// Pascal unit
#include <Tabs.hpp>	// Pascal unit
#include <Docktabset.hpp>	// Pascal unit
#include <Percentagedocktree.hpp>	// Pascal unit
#include <Extdlgs.hpp>	// Pascal unit
#include <Mapi.hpp>	// Pascal unit
#include <Extactns.hpp>	// Pascal unit
#include <Actnmenus.hpp>	// Pascal unit
#include <Actnman.hpp>	// Pascal unit
#include <Platformdefaultstyleactnctrls.hpp>	// Pascal unit
#include <Tabdock.hpp>	// Pascal unit
#include <Basedock.hpp>	// Pascal unit
#include <Deskutil.hpp>	// Pascal unit
#include <Deskform.hpp>	// Pascal unit
#include <Dockform.hpp>	// Pascal unit
#include <Msxmldom.hpp>	// Pascal unit
#include <Xmldom.hpp>	// Pascal unit
#include <Xmlintf.hpp>	// Pascal unit
#include <Toolsapi.hpp>	// Pascal unit
#include <Proxies.hpp>	// Pascal unit
#include <Designeditors.hpp>	// Pascal unit
#include <Sqltimst.hpp>	// Pascal unit
#include <Fmtbcd.hpp>	// Pascal unit
#include <Widestrings.hpp>	// Pascal unit
#include <Db.hpp>	// Pascal unit
#include <Alxpvs.hpp>	// Pascal unit
#include <Advcodelistdd.hpp>	// Pascal unit
#include <Apxpvs.hpp>	// Pascal unit
#include <Asxpvs.hpp>	// Pascal unit
#include <Advspin.hpp>	// Pascal unit
#include <Cabfiles.hpp>	// Pascal unit
#include <Btnxpvs.hpp>	// Pascal unit
#include <Dblogdlg.hpp>	// Pascal unit
#include <Dbpwdlg.hpp>	// Pascal unit
#include <Dbctrls.hpp>	// Pascal unit
#include <Inspxpvs.hpp>	// Pascal unit
#include <Inspdd.hpp>	// Pascal unit
#include <Inspectorbar.hpp>	// Pascal unit
#include <Planxpvs.hpp>	// Pascal unit
#include <Planhtml.hpp>	// Pascal unit
#include <Planner.hpp>	// Pascal unit
#include <Plannercal.hpp>	// Pascal unit
#include <Adveddd.hpp>	// Pascal unit
#include <Advedit.hpp>	// Pascal unit
#include <Aebxpvs.hpp>	// Pascal unit
#include <Dbplannerdatepicker.hpp>	// Pascal unit
#include <Todoxpvs.hpp>	// Pascal unit
#include <Todolist.hpp>	// Pascal unit
#include <Hotspoteditor.hpp>	// Pascal unit
#include <Htmlxpvs.hpp>	// Pascal unit
#include <Htmlchklist.hpp>	// Pascal unit
#include <Axctrls.hpp>	// Pascal unit
#include <Appevnts.hpp>	// Pascal unit
#include <Treeintf.hpp>	// Pascal unit
#include <Toplevels.hpp>	// Pascal unit
#include <Stfilsys.hpp>	// Pascal unit
#include <Idehelp.hpp>	// Pascal unit
#include <Componentdesigner.hpp>	// Pascal unit
#include <Vcleditors.hpp>	// Pascal unit
#include <Parxpvs.hpp>	// Pascal unit
#include <Parhtml.hpp>	// Pascal unit
#include <Paramchklist.hpp>	// Pascal unit
#include <Plannerdatepicker.hpp>	// Pascal unit
#include <Plannermaskdatepicker.hpp>	// Pascal unit
#include <Plannermonthview.hpp>	// Pascal unit
#include <Dbtables.hpp>	// Pascal unit
#include <Dbadvgrid.hpp>	// Pascal unit
#include <Advcardlist.hpp>	// Pascal unit
#include <Advmenuutil.hpp>	// Pascal unit
#include <Advmenus.hpp>	// Pascal unit
#include <Advtbxpvs.hpp>	// Pascal unit
#include <Advdwm.hpp>	// Pascal unit
#include <Advtoolbar.hpp>	// Pascal unit
#include <Advshapebutton.hpp>	// Pascal unit
#include <Outlookgroupedlist.hpp>	// Pascal unit
#include <Advoutlooklist.hpp>	// Pascal unit
#include <Acxpvs.hpp>	// Pascal unit
#include <Advofficepager.hpp>	// Pascal unit
#include <Taskdialog.hpp>	// Pascal unit
#include <Atbxpvs.hpp>	// Pascal unit
#include <Gdipfill.hpp>	// Pascal unit
#include <Advsmootheddd.hpp>	// Pascal unit
#include <Advsmoothedit.hpp>	// Pascal unit
#include <Advsmoothxpvs.hpp>	// Pascal unit
#include <Advsmooththeme.hpp>	// Pascal unit
#include <Advsmoothlistboxdragdrop.hpp>	// Pascal unit
#include <Advsmoothimagelistboxdragdrop.hpp>	// Pascal unit
#include <Advsmoothimagelistbox.hpp>	// Pascal unit
#include <Advsmoothdockdragdrop.hpp>	// Pascal unit
#include <Advexplorertreeview.hpp>	// Pascal unit

//-- user supplied -----------------------------------------------------------

namespace Tmsded2010
{
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------

}	/* namespace Tmsded2010 */
using namespace Tmsded2010;
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// Tmsded2010HPP
