  ErrNoAdapter='Raporttiin linkitettyä adapteria ei ole';
  ErrTooManySheets='Taulukkoja ei voi lisätä enempää';

  ErrNoDataSet='Tietojoukkoa %s ei löydy';
  ErrNoPropDefined='Ominaisuus "%s" ei ole määritelty tai sitä ei ole julkaistu';
  ErrBadProp='Virhe haettaessa ominaisuutta "%s". Tarkista, onko se tyypiltään "variant"';
  ErrTooManyDimensions='Ominaisuudessa "%s" on vain %d ulottuvuutta';
  ErrIndexOutBounds='Indeksi "%d" ominaisuudessa "%s" ei ole alueella %d-%d';

  ErrInvalidDrawingType='Kuvatyyppi "%s" on virheellinen';

  ErrNoOpenFile='Yhtään tiedostoa ei ole avoinna';
  ErrCantFindFile='Tiedostoa "%s" ei löydy';

  ErrNoTemplate='Virhe: %s '#13#10'Tarkista, että aktiivinen projekti ("%s") on oikea';

  ErrDocumentNotSaved='Asiakirjaa ei tallennettu';

  ErrFieldNil='Nil-kenttä';
  ErrDupField='Kenttä "%s" on jo olemassa';
  ErrFieldNotFound='Kenttää "%s" ei ole olemassa';
  ErrInvalidColumnCount='Sarakkeiden määrä on epäkelpo';

  MsgAbout='FlexCel Studio %s  Lataa viimeisin versio osoitteesta http://www.tmssoftware.com';

  TxtDatasets='Tietojoukot';
  TxtProperties='Ominaisuudet';
  TxtExtras=' Ekstrat'; //extra space so it's sorted first

  TxtFileModified='Tiedostoa %s on muutettu. Haluatko tallentaa sen?';
  TxtFileModifiedCaption='Varoitus';
  TxtEditing='Muokataan: %s';
  TxtEditTemplate='Mallin %s muokkaus';
  TxtRefreshTemplate='Valitse kansio, jossa alkuperäiset tiedostot sijaitsevat';
  TxtTemplateStoreRefreshed='Template Store on päivitetty';

  TxtDeleteRange='Poistetaanko alue "%s"?';
  TxtDeleteRangeCaption='Vahvista';

  TxtNamedRangeFormula='=''%s''!%s';

  ErrComponentIsNotXlsDataSet='Komponentti "%s" ei tue IXlsDataSet-rajapintaa';
  ErrUseFasterAdapter='Tämä komponentti ei tue OLE-adapteria';

  TxtTrue='TOSI';
  TxtFalse='EPÄTOSI';

  ErrInvalidWmf='Wmf-tiedosto on epäkelpo';

  TxtSepLog='###################################################################';
  TxtCheckHeader='Tarkistetaan, onko raportti %s yhtäpitävä mallin %s kanssa...';
  TxtError='Virhe: ';
  TxtOK='OK';
  ErrInvalidRangeName='Virhe: Epäkelpo alueen nimi: %s';
  ErrRangeNameNotFound='Virhe: Tietojoukkoa "%s" alueen nimelle "%s" ei löytynyt';
  ErrRangeNameInvalidType='Virhe: Komponentti "%s" alueen nimelle "%s" on epäkelpo tämäntyyppiselle FlexCelReportille';

  ErrCheckCellDots='Solu rivillä %d, sarakkessa %d, taulukossa %d sisältönään "%s" sisältää "..."-merkin, joka ei koostu kolmesta pisteestä ("." "." ".").';
  ErrCheckDotCommandsCol='Solu rivillä %d, sarakkessa %d, taulukossa %d sisältönään "%s" ei ole ensimmäisessä sarakkeessa';
  ErrInvalidCellDB='Solu rivillä %d, sarakkessa %d, taulukossa %d sisältönään "%s" viittaa tietojoukkoon, jota ei ole olemassa.';
  ErrInvalidCellDB2='Solu rivillä %d, sarakkessa %d, taulukossa %d sisältönään "%s" viittaa epäkelpoon tietojoukkoon.';
  ErrInvalidField='Solu rivillä %d, sarakkessa %d, taulukossa %d sisältönään "%s" viittaa epäkelpoon kenttään.';
  ErrInvalidPagesField='PagesDatasetField "%s" ei ole PagesDataSetin "%s" olemassaoleva kenttä';
  ErrFieldOutsideRange='Solu rivillä %d, sarakkessa %d, taulukossa %d sisältönään "%s" ei sisälly mihinkään nimettyyn alueeseen';

  ErrInvalidImageDB='Kuva taulukossa %d, nimeltään "%s", viittaa epäkelpoon tietojoukkoon.';
  ErrInvalidImageField='Kuva taulukossa %d, nimeltään "%s", viittaa epäkelpoon kenttään.';
  ErrInvalidImageType='Kuva taulukossa %d, nimeltään "%s", sisältää epäkelvon ImageTypen (%s).';

  ErrTemplateNotRefreshed='TemplateStore "%s":n tiedostot ovat vanhempia kuin levyllä olevat. TemplateStoren päivittäminen on suositeltavaa.';

  ErrNoAdvStrGrid='Tälle komponentille ei ole osoitettu AdvStringGridiä';
  ErrInvalidSheetName='Epäkelpo taulukon nimi: "%s"';

  ErrInvalidNameForARange='Invalid named range: "%s"';

