  ErrNoAdapter='Il n''existe pas d''adaptateur lié au rapport';
  ErrTooManySheets='Le nombre maximum de feuilles a été atteint';

  ErrNoDataSet='Impossible de trouver le dataset %s';
  ErrNoPropDefined='La propriété "%s" n''a pas  été définie ou n''est pas publiée';
  ErrBadProp='Erreur lors de la recherche de la propriété "%s". Prière de vérifier si son type est "variant"';
  ErrTooManyDimensions='La propriété "%s" n''a que %d dimensions';
  ErrIndexOutBounds='L''indice "%d" de la propriété "%s" doit être compris entre %d et %d';

  ErrInvalidDrawingType='Le type "%s" de l''image est non valide';

  ErrNoOpenFile='Aucun fichier ouvert';
  ErrCantFindFile='Fichier "%s" non trouvé';

  ErrNoTemplate='Erreur: %s '#13#10'Prière de vérifier que le projet actif ("%s") est correct';

  ErrDocumentNotSaved='Document non sauvé';

  ErrFieldNil='Nil field';
  ErrDupField='Duplicated Field Name: "%s"';
  ErrFieldNotFound='Field not found: "%s"';
  ErrInvalidColumnCount='Invalid column count';

  MsgAbout='FlexCel Studio %s  Dernière version disponible sur le site http://www.tmssoftware.com';

  TxtDatasets='Datasets';
  TxtProperties='Propriétés';
  TxtExtras=' Extras'; //extra space so it's sorted first

  TxtFileModified='Le fichier %s a été modifié. Faut-il le sauvegarder ?';
  TxtFileModifiedCaption='Attention';
  TxtEditing='Edition de %s en cours';
  TxtEditTemplate='Edition du canevas: %s';
  TxtRefreshTemplate='Sélectionnez le répertoire contenant les fichiers d''origine';
  TxtTemplateStoreRefreshed='Le canevas sauvegardé a été mis à jour';

  TxtDeleteRange='Effacer la région "%s"?';
  TxtDeleteRangeCaption='Confirmation';

  TxtNamedRangeFormula='=''%s''!%s';

  ErrComponentIsNotXlsDataSet='Component "%s" does not supports interface IXlsDataSet';

  ErrUseFasterAdapter='This component does not supports OLE adapter';

  TxtTrue='TRUE';
  TxtFalse='FALSE';

  ErrInvalidWmf='Wmf file is invalid';

  TxtSepLog='###################################################################';
  TxtCheckHeader='Checking report %s with template %s...';
  TxtError='Error: ';
  TxtOK='OK';
  ErrInvalidRangeName='Error: Invalid Range name: %s';
  ErrRangeNameNotFound='Error: Dataset "%s" for Range name "%s" not found';
  ErrRangeNameInvalidType='Error: Component "%s" for Range name "%s" is not valid for this kind of FlexCelReport';

  ErrCheckCellDots='Cell at Row %d, Column %d, Sheet %d with value "%s" has a "..." character that is not 3 dots ("." "." ".").';
  ErrCheckDotCommandsCol='Cell at Row %d, Column %d, Sheet %d with value "%s" is not on first column';
  ErrInvalidCellDB='Cell at Row %d, Column %d, Sheet %d with value "%s" refers to a non existing dataset.';
  ErrInvalidCellDB2='Cell at Row %d, Column %d, Sheet %d with value "%s" refers to an invalid dataset.';
  ErrInvalidField='Cell at Row %d, Column %d, Sheet %d with value "%s" refers to an invalid field.';
  ErrInvalidPagesField='PagesDatasetField "%s" is not an existing field of PagesDataSet "%s"';
  ErrFieldOutsideRange='Cell at Row %d, Column %d, Sheet %d with value "%s" is not included in any named range';

  ErrInvalidImageDB='Image at Sheet %d named "%s" refers to an invalid dataset.';
  ErrInvalidImageField='Image at Sheet %d named "%s" refers to an invalid field.';
  ErrInvalidImageType='Image at Sheet %d named "%s" has an invalid ImageType (%s).';

  ErrTemplateNotRefreshed='The files at the TemplateStore "%s" are older than the ones on the disk. You should Refresh it.';

  ErrNoAdvStrGrid='There is no AdvStringGrid assigned to this component';
  ErrInvalidSheetName='Invalid sheet name: "%s"';

  ErrInvalidNameForARange='Invalid named range: "%s"';

