  ErrNoAdapter='Kein Adapter mit dem Report verbunden';
  ErrTooManySheets='Es wurde versucht mehr Seiten als maximal erlaubt einzufügen';

  ErrNoDataSet='Konnte Datensatz %s nicht finden';
  ErrNoPropDefined='Eigenschaft "%s" wurde nicht definiert, oder ist nicht published';
  ErrBadProp='Error beim Zugriff auf Eigenschaft "%s". Stellen Sie sicher das es vom Typ Variant ist';
  ErrTooManyDimensions='Die Eigenschaft "%s" hat nur %d Dimensionen';
  ErrIndexOutBounds='Der Index "%d" der Eigenschaft "%s" ist nicht im Bereich %d-%d';

  ErrInvalidDrawingType='Zeichen-typ "%s" ist ungültig';

  ErrNoOpenFile='Keine Datei geöffnet';
  ErrCantFindFile='Konnte Datei "%s" nicht finden';

  ErrNoTemplate='Fehler: %s '#13#10'Überprüfen Sie ob das aktive Projekt ("%s") das aktuelle Projekt ist';

  ErrDocumentNotSaved='Dokument wurde nicht gespeichert';

  ErrFieldNil='Nil Feld';
  ErrDupField='Doppelt vorhandener Feldname: "%s"';
  ErrFieldNotFound='Feld nicht gefunden: "%s"';
  ErrInvalidColumnCount='Ungültige Spaltenanzahl';

  MsgAbout='FlexCel Studio %s  Die aktuelle Version gibt es hier: http://www.tmssoftware.com';

  TxtDatasets='Tabellen';
  TxtProperties='Eigenschaften';
  TxtExtras=' Extras'; //extra space so it's sorted first

  TxtFileModified='Datei %s wurde geändert. Möchten Sie sie speichern?';
  TxtFileModifiedCaption='Warnung';
  TxtEditing='Bearbeite %s';
  TxtEditTemplate='Bearbeite Template: %s';
  TxtRefreshTemplate='Wählen Sie das Verzeichnis der Originaldateien';
  TxtTemplateStoreRefreshed='Der Template Speicher wurde aktualisiert';

  TxtDeleteRange='Bereich löschen "%s"?';
  TxtDeleteRangeCaption='Bestätigen';

  TxtNamedRangeFormula='=''%s''!%s';

  ErrComponentIsNotXlsDataSet='Komponente "%s" unterstützt interface IXlsDataSet nicht';
  ErrUseFasterAdapter='Diese Komponente unterstützt den OLE adapter nicht';

  TxtTrue='TRUE';
  TxtFalse='FALSE';

  ErrInvalidWmf='Wmf Datei ist ungültig';

  TxtSepLog='###################################################################';
  TxtCheckHeader='Überprüfe Report %s mit Template %s...';
  TxtError='Fehler: ';
  TxtOK='OK';
  ErrInvalidRangeName='Fehler: Ungültiger Bereich Name: %s';
  ErrRangeNameNotFound='Fehler: Datensatz "%s" für Bereich Name "%s" nicht gefunden';
  ErrRangeNameInvalidType='Fehler: Komponente "%s" für Bereich Name "%s" ist ungültig für diese Art von FlexCelReport';

  ErrCheckCellDots='Zelle in Zeile %d, Spalte %d, Sheet %d mit Wert "%s" hat ein "..." Zeichen, welches nicht den 3 Punkten entspricht ("." "." ".").';
  ErrCheckDotCommandsCol='Zelle in Zeile %d, Spalte %d, Sheet %d mit Wert "%s" ist nicht die erste Spalte';
  ErrInvalidCellDB='Zelle in Zeile %d, Spalte %d, Sheet %d mit Wert "%s" zeigt auf einen nicht existierenden Datensatz';
  ErrInvalidCellDB2='Zelle in Zeile %d, Spalte %d, Sheet %d mit Wert "%s" zeigt auf einen ungültigen Datensatz.';
  ErrInvalidField='Zelle in Zeile %d, Spalte %d, Sheet %d mit Wert "%s" zeigt auf ein ungültiges Feld.';
  ErrInvalidPagesField='PagesDatasetField "%s" ist kein existierendes Feld vom PagesDataSet "%s"';
  ErrFieldOutsideRange='Zelle in Zeile %d, Spalte %d, Sheet %d mit Wert "%s" ist in keinem Namensbereich';

  ErrInvalidImageDB='Bild "%s" im Sheet %d zeigt auf einen ungültigen Datensatz.';
  ErrInvalidImageField='Bild "%s" im Sheet %d zeigt auf ein ungültiges Feld';
  ErrInvalidImageType='Bild "%s" im Sheet %d hat einen ungültigen Bildtyp (%s).';

  ErrTemplateNotRefreshed='Die Dateien im TemplateStore "%s" sind älter als die Dateien auf der Festplatte. Sie sollten sie aktualisieren.';

  ErrNoAdvStrGrid='There is no AdvStringGrid assigned to this component';
  ErrInvalidSheetName='Invalid sheet name: "%s"';

   ErrInvalidNameForARange='Invalid named range: "%s"';

