  ErrNoAdapter='Non esiste un adattatore collegato con il report';
  ErrTooManySheets='Tentativo di scrivere più fogli di quelli permessi';

  ErrNoDataSet='Impossibile trovare il dataset %s';
  ErrNoPropDefined='La proprietà "%s" non è stata definita o non è pubblicata';
  ErrBadProp='Errore al recuperare la proprietà "%s". Verificare che sia di tipo variant';
  ErrTooManyDimensions='La proprietà "s" ha solamente %d dimensioni';
  ErrIndexOutBounds='L''indice "%d" della proprietà "%s" non è contenuto nell''intervallo %d-%d';

  ErrInvalidDrawingType='Il tipo di immagine "%s" non è valido';

  ErrNoOpenFile='Nessun file aperto';
  ErrCantFindFile='Impossibile trovare il file "%s"';
  ErrCantWriteToFile='Impossibile salvare il file "%s". Verificare che non sia utilizzato da un altro utente';

  ErrNoTemplate='Errore: %s '#13#10'Verificare che il progetto attivato ("%s") sia quello corretto';
  ErrDocumentNotSaved='Il documento non è stato salvato';

  ErrFieldNil='Campo nil';
  ErrDupField='Duplicated Field Name: "%s"';
  ErrFieldNotFound='Field not found: "%s"';
  ErrInvalidColumnCount='Invalid column count';

  MsgAbout='FlexCel Studio %s  Scaricati l''ultima versione in http://www.tmssoftware.com';

  TxtDatasets='Datasets';
  TxtProperties='Proprietà';
  TxtExtras=' Extra'; //extra space so it's sorted first

  TxtFileModified='Il file %s è stato modificato. Vuoi salvarlo?';
  TxtFileModifiedCaption='Avviso';
  TxtEditing='Modificando %s';
  TxtEditTemplate='Modificare Template: %s';
  TxtRefreshTemplate='Selezionare la cartella dove si trovano i files originali';
  TxtTemplateStoreRefreshed='Il Template Store è stato aggiornato';

  TxtDeleteRange='Eliminare intervallo "%s"?';
  TxtDeleteRangeCaption='Confermare';

  TxtNamedRangeFormula='=''%s''!%s';

  ErrComponentIsNotXlsDataSet='Component "%s" does not supports interface IXlsDataSet';
  ErrUseFasterAdapter='This component does not supports OLE adapter';

  TxtTrue='TRUE';
  TxtFalse='FALSE';

  ErrInvalidWmf='Wmf file is invalid';

  TxtSepLog='###################################################################';
  TxtCheckHeader='Checking report %s with template %s...';
  TxtError='Error: ';
  TxtOK='OK';
  ErrInvalidRangeName='Error: Invalid Range name: %s';
  ErrRangeNameNotFound='Error: Dataset "%s" for Range name "%s" not found';
  ErrRangeNameInvalidType='Error: Component "%s" for Range name "%s" is not valid for this kind of FlexCelReport';

  ErrCheckCellDots='Cell at Row %d, Column %d, Sheet %d with value "%s" has a "..." character that is not 3 dots ("." "." ".").';
  ErrCheckDotCommandsCol='Cell at Row %d, Column %d, Sheet %d with value "%s" is not on first column';
  ErrInvalidCellDB='Cell at Row %d, Column %d, Sheet %d with value "%s" refers to a non existing dataset.';
  ErrInvalidCellDB2='Cell at Row %d, Column %d, Sheet %d with value "%s" refers to an invalid dataset.';
  ErrInvalidField='Cell at Row %d, Column %d, Sheet %d with value "%s" refers to an invalid field.';
  ErrInvalidPagesField='PagesDatasetField "%s" is not an existing field of PagesDataSet "%s"';
  ErrFieldOutsideRange='Cell at Row %d, Column %d, Sheet %d with value "%s" is not included in any named range';

  ErrInvalidImageDB='Image at Sheet %d named "%s" refers to an invalid dataset.';
  ErrInvalidImageField='Image at Sheet %d named "%s" refers to an invalid field.';
  ErrInvalidImageType='Image at Sheet %d named "%s" has an invalid ImageType (%s).';

  ErrTemplateNotRefreshed='The files at the TemplateStore "%s" are older than the ones on the disk. You should Refresh it.';

  ErrNoAdvStrGrid='There is no AdvStringGrid assigned to this component';
  ErrInvalidSheetName='Invalid sheet name: "%s"';

  ErrInvalidNameForARange='Invalid named range: "%s"';

