  ErrNoAdapter='Brak adaptera zwi¹zanego z raportem';
  ErrTooManySheets='Iloœæ arkuszy przekracza dopuszczalne maksimum';

  ErrNoDataSet='Nie mo¿na odnaleŸæ zbioru danych %s';
  ErrNoPropDefined='W³aœciowœæ "%s" nie zosta³a zdefiniowana lub nie jest publiczna';
  ErrBadProp='B³¹d podczas próby odczytu w³aœciwoœci "%s". SprawdŸ, czy ma typ wariantowy.';
  ErrTooManyDimensions='W³aœciwoœæ "%s" posiada tylko %d wymiary(ów)';
  ErrIndexOutBounds='Indeks "%d" w³aœciwoœæi "%s" jest poza zakresem %d-%d';

  ErrInvalidDrawingType='Nieprawid³owy typ rysowania: "%s"';

  ErrNoOpenFile='Brak otwartego pliku';
  ErrCantFindFile='Nie mo¿na odnaleŸæ pliku "%s"';

  ErrNoTemplate='B³¹d: %s '#13#10'Upewnij siê, czy aktywny projekt ("%s") jest poprawny';

  ErrDocumentNotSaved='Dokument nie zosta³ zapisany';

  ErrFieldNil='Pole zawiera pust¹ wartoœæ (NIL)';
  ErrDupField='Duplikat nazwy pola: "%s"';
  ErrFieldNotFound='Pole nie zosta³o odnalezione: "%s"';
  ErrInvalidColumnCount='Nieprawid³owa iloœæ kolumn';

  MsgAbout='FlexCel Studio %s  Pobierz najnowsz¹ wersjê na http://www.tmssoftware.com';

  TxtDatasets='Zbiory danych';
  TxtProperties='W³aœciwoœci';
  TxtExtras=' Dodatki'; //extra space so it's sorted first

  TxtFileModified='Plik %s zosta³ zmieniony. Czy zachowaæ zmiany?';
  TxtFileModifiedCaption='Ostrze¿enie';
  TxtEditing='Edycja %s';
  TxtEditTemplate='Wzorzec edycji: %s';
  TxtRefreshTemplate='Wska¿ folder, gdzie s¹ umieszczone oryginalne pliki';
  TxtTemplateStoreRefreshed='Magazyn wzorców zosta³ odœwie¿ony';

  TxtDeleteRange='Czy usun¹æ zakres "%s"?';
  TxtDeleteRangeCaption='Potwierdzenie';

  TxtNamedRangeFormula='=''%s''!%s';

  ErrComponentIsNotXlsDataSet='Komponent "%s" nie obs³uguje interfejsu IXlsDataSet';
  ErrUseFasterAdapter='Ten komponent nie obs³uguje adaptera OLE';

  TxtTrue='TRUE';
  TxtFalse='FALSE';

  ErrInvalidWmf='Plik Wmf jest nieprawid³owy';

  TxtSepLog='###################################################################';
  TxtCheckHeader='Sprawdzanie raportu %s ze wzorcem %s...';
  TxtError='B³¹d: ';
  TxtOK='OK';
  ErrInvalidRangeName='B³¹d: Nieprawid³owa nazwa zakresu: %s';
  ErrRangeNameNotFound='B³¹d: Zbiór danych "%s" dla rangi "%s" nie zosta³ znaleziony';
  ErrRangeNameInvalidType='B³¹d: Komponet "%s" dla rangi "%s" jest nieprawid³owy dla tego rodzaju raportu FlexCelReport';

  ErrCheckCellDots='Komórka w wierszu %d, kolumnie %d, arkuszu %d o wartoœci "%s" zawiera "...", które nie s¹ 3 znakami kropki ("." "." ".").';
  ErrCheckDotCommandsCol='Komórka w wierszu %d, kolumnie %d, arkuszu %d o wartoœci "%s" nie znajduje siê w pierwszej kolumnie';
  ErrInvalidCellDB='Komórka w wierszu %d, kolumnie %d, arkuszu %d o wartoœci "%s" odnosi siê do nieistniej¹cego zbioru danych.';
  ErrInvalidCellDB2='Komórka w wierszu %d, kolumnie %d, arkuszu %d o wartoœci "%s" odnosi siê do nieprawid³owego zbioru danych.';
  ErrInvalidField='Komórka w wierszu %d, kolumnie %d, arkuszu %d o wartoœci "%s" odnosi siê do nieprawid³owego pola.';
  ErrInvalidPagesField='PagesDatasetField "%s" nie istnieje jako pole w PagesDataSet "%s"';
  ErrFieldOutsideRange='Komórka w wierszu %d, kolumnie %d, arkuszu %d o wartoœci "%s" nie zosta³a za³¹czona do ¿adnej rangi';

  ErrInvalidImageDB='Grafika w arkuszu %d, o nazwie "%s" odnosi siê do nieprawid³owego zbioru danych.';
  ErrInvalidImageField='Grafika w arkuszu %d, o nazwie "%s" odnosi siê do nieprawid³owego pola.';
  ErrInvalidImageType='Grafika w arkuszu %d, o nazwie "%s" ma nieprawid³owy typ ImageType (%s).';

  ErrTemplateNotRefreshed='Pliki w magazynie TemplateStore "%s" s¹ starsze ni¿ te znajduj¹ce siê na dysku. Czy odœwie¿yæ magazyn wzorców?';

  ErrNoAdvStrGrid='Brak siatki AdvStringGrid pod³¹czonej do komponentu';
  ErrInvalidSheetName='Nieprawid³owa nazwa arkusza: "%s"';

  ErrInvalidNameForARange='Invalid named range: "%s"';

