  ErrNoAdapter='Não existe nenhum adaptador ligado ao relatório'; 
  ErrTooManySheets='Tentativa de incluir mais planilhas que o máximo permitido'; 

  ErrNoDataSet='Não é possível encontrar o dataset %s'; 
  ErrNoPropDefined='A propriedade "%s" não foi definida ou não está publicada'; 
  ErrBadProp='Erro ao tentar reter a propriedade "%s". Verifique se ela é do tipo variant'; 
  ErrTooManyDimensions='A propriedade "%s" tem apenas %d dimensões'; 
  ErrIndexOutBounds='O índice "%d" da propriedade "%s" não está no intervalo %d-%d'; 

  ErrInvalidDrawingType='O tipo de desenho "%s" é inválido'; 

  ErrNoOpenFile='Não existe nenhum arquivo aberto'; 
  ErrCantFindFile='Não é possível encontrar o arquivo "%s"'; 

  ErrNoTemplate='Erro: %s '#13#10'Verifique que o projeto ativo ("%s") é o projeto correto'; 

  ErrDocumentNotSaved='O documento não foi salvo'; 
  ErrFieldNil='Campo nil'; 
  ErrDupField='Nome de Campo duplicado: "%s"'; 
  ErrFieldNotFound='Arquivo não encontrado: "%s"'; 
  ErrInvalidColumnCount='Contador de coluna inválido'; 

  MsgAbout='FlexCel Studio %s Obtenha a última versão no site www.tmssoftware.com';

  TxtDatasets='Datasets';
  TxtProperties='Propriedades'; 
  TxtExtras=' Extras'; 

  TxtFileModified='O arquivo %s foi modificado. Deseja salvá-lo?'; 
  TxtFileModifiedCaption='Aviso'; 
  TxtEditing='Editando %s'; 
  TxtEditTemplate='Editar Modelo: %s'; 
  TxtRefreshTemplate='Selecione a pasta onde os arquivos originais estão'; 
  TxtTemplateStoreRefreshed='O depósito de modelos foi restaurado'; 

  TxtDeleteRange='Excluir o Intervalo?'; 
  TxtDeleteRangeCaption='Confirme'; 

  TxtNamedRangeFormula='=''%s''!%s';

  ErrComponentIsNotXlsDataSet='O componente "%s" não suporta a interface IXlsDataSet'; 
  ErrUseFasterAdapter='Este componente não suporta o adaptador OLE';

  TxtTrue='VERDADEIRO';
  TxtFalse='FALSO';

  ErrInvalidWmf='O arquivo wmf é inválido';

  TxtSepLog='###################################################################';
  TxtCheckHeader='Verificando relatório %s com template %s...';
  TxtError='Erro: ';
  TxtOK='OK';
  ErrInvalidRangeName='Erro: Nome de Intervalo inválido: %s';
  ErrRangeNameNotFound='Erro: o Dataset "%s" para o nome de Intervalo "%s" não existe';
  ErrRangeNameInvalidType='Erro: o Componente "%s" para o nome de Intervalo "%s" não é válido para este tipo de FlexCelReport';

  ErrCheckCellDots='Célula na Linha %d, Coluna %d, Folha %d com valor "%s" tem um caracter "..." que não são 3 pontos separados ("." "." ".").';
  ErrCheckDotCommandsCol='Célula na Linha %d, Coluna %d, Folha %d com valor "%s" não está na primeira coluna';
  ErrInvalidCellDB='Célula na Linha %d, Coluna %d, Folha %d com valor "%s" faz referência a um dataset inexistente.';
  ErrInvalidCellDB2='Célula na Linha %d, Coluna %d, Folha %d com valor "%s" faz referência a um dataset inválido.';
  ErrInvalidField='Célula na Linha %d, Coluna %d, Folha %d com valor "%s" faz referência a um campo inválido.';
  ErrInvalidPagesField='O campo PagesDatasetField "%s" não existe em PagesDataSet "%s"';
  ErrFieldOutsideRange='Célula na Linha %d, Coluna %d, Folha %d com valor "%s" não está dentro de nenhum nome de Intervalo';

  ErrInvalidImageDB='A imagem na folha %d ("%s") faz referência a um dataset inválido.';
  ErrInvalidImageField='A imagem na folha %d ("%s") faz referência a um campo inválido.';
  ErrInvalidImageType='A imagem na folha %d ("%s") é de um tipo inválido.(%s).';

  ErrTemplateNotRefreshed='Os arquivos na TemplateStore "%s" são mais antigos que os arquivos no disco. Você deveria atualizá-los.';

  ErrNoAdvStrGrid='Não existe um AdvStringGrid associado a este componente';
  ErrInvalidSheetName='Nome da folha inválido: "%s"';

  ErrInvalidNameForARange='Nome de Intervalo inválido: "%s"';

