  ErrNoAdapter='К отчету не привязан Adapter';
  ErrTooManySheets='Попытка вставить больше листов, чем допустимо';

  ErrNoDataSet='Не могу найти набор данных %s';
  ErrNoPropDefined='Свойство "%s" не определено или не опубликовано';
  ErrBadProp='Ошибка получения значения свойства "%s". Это должен быть вариант';
  ErrTooManyDimensions='Свойство "%s" имеет только %d размерностей';
  ErrIndexOutBounds='Индекс "%d" свойства "%s" вне диапазона %d-%d';

  ErrInvalidDrawingType='Тип отрисовки "%s" неверен';

  ErrNoOpenFile='Нет открытого файла';
  ErrCantFindFile='Не могу найти файл "%s"';

  ErrNoTemplate='Ошибка: %s '#13#10'Проверьте, правилен ли активный проект ("%s")';

  ErrDocumentNotSaved='Документ не сохранен';

  ErrFieldNil='Поле Nil';
  ErrDupField='Дубликат имени поля: "%s"';
  ErrFieldNotFound='Поле не найдено: "%s"';
  ErrInvalidColumnCount='Неверное число стобцов';

  MsgAbout='FlexCel Studio V %s  Последнюю версию можно получить на http://www.tmssoftware.com';

  TxtDatasets='Datasets';
  TxtProperties='Properties';
  TxtExtras=' Extras';

  TxtFileModified='Файл %s был изменен. Сохранить его?';
  TxtFileModifiedCaption='Внимание';
  TxtEditing='Правка %s';
  TxtEditTemplate='Правка шаблона: %s';
  TxtRefreshTemplate='Выберите папку, в которой находятся оригинальные файлы';
  TxtTemplateStoreRefreshed='Хранилище шаблонов было обновлено';

  TxtDeleteRange='Удалить диапазон "%s"?';
  TxtDeleteRangeCaption='Подтверждение';

  TxtNamedRangeFormula='=''%s''!%s';

  ErrComponentIsNotXlsDataSet='Компонент "%s" не поддерживает интерфейс IXlsDataSet';
  ErrUseFasterAdapter='Этот компонент не поддерживает OLE adapter';

  TxtTrue='TRUE';
  TxtFalse='FALSE';

  ErrInvalidWmf='Файл Wmf неверен';

  TxtSepLog='###################################################################';
  TxtCheckHeader='Сравнивается отчет %s с шаблоном %s...';
  TxtError='Ошибка: ';
  TxtOK='OK';
  ErrInvalidRangeName='Ошибка: Неправильное Имя диапазона: %s';
  ErrRangeNameNotFound='Ошибка: Dataset "%s" для имени диапазона "%s" не найден';
  ErrRangeNameInvalidType='Ошибка: Компонент "%s" для имени диапазона "%s" не действителен для данного типа FlexCelReport';

  ErrCheckCellDots='Ячейка в Строке %d, Колонке %d, на Листе %d со значением "%s" имеет "..." символ, который не является троеточием ("." "." ".").';
  ErrCheckDotCommandsCol='Ячейка в Строке %d, Колонке %d, на Листе %d со значением "%s" не в первой Колонке';
  ErrInvalidCellDB='Ячейка в Строке %d, Колонке %d, на Листе %d со значением "%s" ссылается на несуществующий dataset.';
  ErrInvalidCellDB2='Ячейка в Строке %d, Колонке %d, на Листе %d со значением "%s" ссылается на неверный dataset.';
  ErrInvalidField='Ячейка в Строке %d, Колонке %d, на Листе %d со значением "%s" ссылается на неверное поле.';
  ErrInvalidPagesField='PagesDatasetField "%s" несуществующее поле PagesDataSet "%s"';
  ErrFieldOutsideRange='Ячейка в Строке %d, Колонке %d, на Листе %d со значением "%s" не включена ни в какой именованный диапазон';

  ErrInvalidImageDB='Изображение на Листе %d, имеющее имя "%s" ссылается на неправильный dataset.';
  ErrInvalidImageField='Изображение на Листе %d, имеющее имя "%s" ссылается на неверное поле.';
  ErrInvalidImageType='Изображение на Листе %d, имеющее имя "%s" имеет неправильный ImageType (%s).';

  ErrTemplateNotRefreshed='Файлы в TemplateStore "%s" имеют более ранние версии чем на диске. Вы должны обновить их.';

  ErrNoAdvStrGrid='Нет AdvStringGrid assigned этому компоненту';
  ErrInvalidSheetName='Неправильное имя Листа: "%s"';

  ErrInvalidNameForARange='Invalid named range: "%s"';

