  ErrNoAdapter='Nu aveti nici un adaptor (Adapter) legat la raport';
  ErrTooManySheets='Ati incercat sa adaugati mai multe foi de calcul decat maximum permis';

  ErrNoDataSet='Nu pot gasi Dataset %s';
  ErrNoPropDefined='Proprietatea "%s" nu este definita (sau publicata)';
  ErrBadProp='Eroare la extragerea valorii proprietatii "%s". Verificati daca este tip Variant';
  ErrTooManyDimensions='Proprietatea "%s" are numai %d dimensiuni';
  ErrIndexOutBounds='Indexul "%d" al proprietatii "%s" nu este in domeniul %d-%d';

  ErrInvalidDrawingType='Forma grafica (Drawing) "%s" invalida';

  ErrNoOpenFile='Nu aveti nici un fisier deschis';
  ErrCantFindFile='Nu pot gasi fisierul "%s"';

  ErrNoTemplate='Eroare: %s '#13#10'Verificati daca proiectul activ ("%s") este cel corect';

  ErrDocumentNotSaved='Documentul nu a fost salvat';

  ErrFieldNil='Camp nul (Nil)';
  ErrDupField='Nume camp duplicat: "%s"';
  ErrFieldNotFound='Fisier inexistent: "%s"';
  ErrInvalidColumnCount='Numar de coloana invalid (inexistent)';

  MsgAbout='FlexCel Studio %s  Urmariti http://www.tmssoftware.com pt ultima versiune';

  TxtDatasets='Datasets';
  TxtProperties='Properties';
  TxtExtras=' Extras'; //extra space so it's sorted first

  TxtFileModified='Fisierul %s a fost modificat. Doriti sa-l salvati?';
  TxtFileModifiedCaption='Avertisment';
  TxtEditing='In editare %s';
  TxtEditTemplate='Editare model (template): %s';
  TxtRefreshTemplate='Selectati directorul unde sunt fisierele originale';
  TxtTemplateStoreRefreshed='Colectia de modele (Template Store) a fost actualizata';

  TxtDeleteRange='Stergeti domeniul "%s"?';
  TxtDeleteRangeCaption='Confirmati';

  TxtNamedRangeFormula='=''%s''!%s';

  ErrComponentIsNotXlsDataSet='Componenta "%s" nu suporta interfata IXlsDataSet';
  ErrUseFasterAdapter='Aceasta componenta nu suporta adaptor-ul OLE (OLE Adapter)';

  TxtTrue='TRUE';
  TxtFalse='FALSE';

  ErrInvalidWmf='Fisierul WMF este invalid';

  TxtSepLog='###################################################################';
  TxtCheckHeader='Checking report %s with template %s...';
  TxtError='Error: ';
  TxtOK='OK';
  ErrInvalidRangeName='Error: Invalid Range name: %s';
  ErrRangeNameNotFound='Error: Dataset "%s" for Range name "%s" not found';
  ErrRangeNameInvalidType='Error: Component "%s" for Range name "%s" is not valid for this kind of FlexCelReport';

  ErrCheckCellDots='Cell at Row %d, Column %d, Sheet %d with value "%s" has a "..." character that is not 3 dots ("." "." ".").';
  ErrCheckDotCommandsCol='Cell at Row %d, Column %d, Sheet %d with value "%s" is not on first column';
  ErrInvalidCellDB='Cell at Row %d, Column %d, Sheet %d with value "%s" refers to a non existing dataset.';
  ErrInvalidCellDB2='Cell at Row %d, Column %d, Sheet %d with value "%s" refers to an invalid dataset.';
  ErrInvalidField='Cell at Row %d, Column %d, Sheet %d with value "%s" refers to an invalid field.';
  ErrInvalidPagesField='PagesDatasetField "%s" is not an existing field of PagesDataSet "%s"';
  ErrFieldOutsideRange='Cell at Row %d, Column %d, Sheet %d with value "%s" is not included in any named range';

  ErrInvalidImageDB='Image at Sheet %d named "%s" refers to an invalid dataset.';
  ErrInvalidImageField='Image at Sheet %d named "%s" refers to an invalid field.';
  ErrInvalidImageType='Image at Sheet %d named "%s" has an invalid ImageType (%s).';

  ErrTemplateNotRefreshed='The files at the TemplateStore "%s" are older than the ones on the disk. You should Refresh it.';

  ErrNoAdvStrGrid='There is no AdvStringGrid assigned to this component';
  ErrInvalidSheetName='Invalid sheet name: "%s"';

   ErrInvalidNameForARange='Invalid named range: "%s"';

