  ErrNoAdapter='No hay un Adaptador asociado al reporte';
  ErrTooManySheets='Se están intentando crear demasiadas páginas';

  ErrNoDataSet='No se puede encontrar el dataset %s';
  ErrNoPropDefined='No se ha definido la propiedad "%s" o no es published';
  ErrBadProp='Error al recuperar la propiedad "%s". Verifique que sea del tipo variant';
  ErrTooManyDimensions='La propiedad "s" solo tiene %d dimensiones';
  ErrIndexOutBounds='El indice "%d" de la propiedad "%s" no está en el rango %d-%d';

  ErrInvalidDrawingType='El tipo de imagen "%s" no es válido';

  ErrNoOpenFile='No hay ningun archivo abierto';
  ErrCantFindFile='No se puede encontrar el archivo "%s"';
  ErrCantWriteToFile='No se puede grabar en el archivo "%s". Compruebe que no este siendo usado por otro usuario';

  ErrNoTemplate='Error: %s '#13#10'Verifique que el proyecto activado ("%s") es el correcto';
  ErrDocumentNotSaved='El documento no fue grabado';

  ErrFieldNil='El campo es nil';
  ErrDupField='El campo ya existe: "%s"';
  ErrFieldNotFound='El campo no existe: "%s"';
  ErrInvalidColumnCount='Número de columnas inválido';

  MsgAbout='FlexCel Studio %s  Consiga la ultima version en http://www.tmssoftware.com';

  TxtDatasets='Datasets';
  TxtProperties='Properties';
  TxtExtras=' Extras'; //extra space so it's sorted first

  TxtFileModified='El archivo %s fue modificado. ¿Grabar?';
  TxtFileModifiedCaption='Advertencia';
  TxtEditing='Editando %s';
  TxtEditTemplate='Editar Template: %s';
  TxtRefreshTemplate='Seleccione el directorio donde están los archivos originales';
  TxtTemplateStoreRefreshed='El Template Store ha sido refrescado';

  TxtDeleteRange='Borrar rango "%s"?';
  TxtDeleteRangeCaption='Confirmar';

  TxtNamedRangeFormula='=''%s''!%s';

  ErrComponentIsNotXlsDataSet='El componente "%s" no soporta la interfaz IXlsDataSet';

  ErrUseFasterAdapter='Este componente no soporta OLE adapter';

  TxtTrue='VERDADERO';
  TxtFalse='FALSO';

  ErrInvalidWmf='El Archivo Wmf es inválido';

  TxtSepLog='###################################################################';
  TxtCheckHeader='Verificando reporte %s con template %s...';
  TxtError='Error: ';
  TxtOK='OK';
  ErrInvalidRangeName='Error: Nombre de rango inválido: %s';
  ErrRangeNameNotFound='Error: El Dataset "%s" para el nombre de rango "%s" no existe';
  ErrRangeNameInvalidType='Error: El componente "%s" para el nombre de rango "%s" no es válido para este tipo de FlexCelReport';

  ErrCheckCellDots='La celda en Fila %d, Columna %d, Hoja %d con valor "%s" tiene un carácter "..." que on son 3 puntos separados ("." "." ".").';
  ErrCheckDotCommandsCol='La celda en Fila %d, Columna %d, Hoja %d con valor "%s" no está en la primer columna';
  ErrInvalidCellDB='La celda en Fila %d, Columna %d, Hoja %d con valor "%s" hace referencia a un dataset inexistente.';
  ErrInvalidCellDB2='La celda en Fila %d, Columna %d, Hoja %d con valor "%s" hace referencia a un dataset inválido.';
  ErrInvalidField='La celda en Fila %d, Columna %d, Hoja %d con valor "%s" hace referencia a un campo inválido.';
  ErrInvalidPagesField='El campo PagesDatasetField "%s" no exite en PagesDataSet "%s"';
  ErrFieldOutsideRange='La celda en Fila %d, Columna %d, Hoja %d con valor "%s" no está dentro de ningún nombre de rango';

  ErrInvalidImageDB='La imagen en la hoja %d ("%s") hace referencia a un dataset inválido.';
  ErrInvalidImageField='La imagen en la hoja %d ("%s") hace referencia a un campo inválido.';
  ErrInvalidImageType='La imagen en la hoja %d ("%s") es de tipo inválido.(%s).';

  ErrTemplateNotRefreshed='Los archivos de la TemplateStore "%s" son más antiguos que los archivos en el disco. Deberia refrescarla.';

  ErrNoAdvStrGrid='No hay una AdvStringGrid asociada con este componente';
  ErrInvalidSheetName='Nombre de hoja inválido: "%s"';

  ErrInvalidNameForARange='Nombre de rango inválido: "%s"';
