  ErrFileIsNotXLS='O arquivo "%s" é inválido'; 
  ErrCantReadFile='Não é possível ler o arquivo "%s"'; 
  ErrExcelInvalid= 'Erro ao ler os registros do Excel. Arquivo inválido'; 
  ErrCantWriteOutput='Impossível criar o arquivo de saída "%s"'; //'Can''t create output file "%s"';
  ErrCantWrite='Erro ao gravar o arquivo de saída'; //'Error writing output file';

  ErrFileNotFound='Impossível encontrar o arquivo "%s"'; //'Can''t find file "%s"';
  ErrStreamNotFound='Não é possível abrir a Stream "%s"'; 

  ErrExtRefsNotSupported='As referências externas a outra folha de cálculo (Workbook) não são suportadas por FlexCel'; 

  ErrWrongExcelRecord='O registro com ID 0x%x é inválido'; 

  ErrBadToken='Erro ao ler a fórmula, o Token ID: 0x%2x não é suportado'; 
  ErrBadFormula='A fórmula na Linha %d, Coluna %d não é suportada. Token ID: 0x%2x'; 
  ErrBadName='Erro na planilha: %s. Token ID: 0x%2x'; 
  ErrBadCF='Erro no Formato Condicional. Token ID: 0x%2x'; 
  ErrBadChartFormula='Erro na fórmula do Gráfico. Token ID: 0x%2x'; 

  Err3DRef='Encontrada uma referência para outra planilha numa fórmula que não suporta isto'; 

  ErrReadingRecord='Erro ao ler o registro'; 

  ErrInvalidVersion='O arquivo de modelo foi salvo com uma versão inválida do Excel'; 

  ErrTooManyEntries= 'Existem muitas entradas para este tipo de registro (%d para um máximo de %s)'; 
  ErrRecordNotSupported='O modelo contém um registro não suportado: %4x'; 

  ErrSectionNotLoaded='Uma seção da folha de cálculo (WorkBook) não foi carregada'; 

  ErrInvalidContinue='Tentativa de adicionar mais de um registro CONTÍNUO para o mesmo registro'; 
  ErrStringTooLarge='String muito grande'; 
  ErrInvalidDrawing='O arquivo tem um registro de desenho não suportado'; 
  ErrInvalidCF='Formato condicinal inválido'; 

  ErrDuplicatedSheetName='O nome da folha já existe'; 

  ErrDupRow='Registro de LINHA duplicado'; 
  ErrRowMissing='Não existe o registro de LINHA para a linha %d'; 

  ErrBadCopyRows='Argumento inválido para chamar InsertAndCopyRows'; 
  ErrInvalidSheetNo='Número de folha %d inválido. deve ser entre %d e %d'; 

  ErrBadRowCount='O número do registro de LINHA não é o mesmo que o contador de células'; 

  ErrEscherNotLoaded='O registro Escher não está totalmente carregado'; 
  ErrLoadingEscher='Erro ao carregar o registro Escher'; 
  ErrBStroreDuplicated='Erro ao carregar o registro Escher. BStore duplicado'; 
  ErrDgDuplicated='Erro ao carregar o registro Escher. Dg duplicado'; 
  ErrDggDuplicated='Erro ao carregar o registro Escher. Dgg duplicado'; 
  ErrsolverDuplicated='Erro ao carregar o registro Escher. Solver container duplicado'; 

  ErrChangingEscher='Erro ao processar o registro Escher'; 

  ErrInternal='FlexCel: Erro de lógica'; 

  ErrCantCopyPictFmla='Impossível copiar objetos OLE embutidos na Folha'; 

  ErrInvalidErrStr='Código de erro da célula inválido: %s'; 
  ErrInvalidCellValue='Valor de célula inválido: %s'; 

  ErrCantWriteToFile='Não é possível gravar no arquivo "%s". Verifique se se ele não está sendo usado por outro usuário'; 

  ErrShrFmlaNotFound='Não é possível encontrar a Fórmula Compartilhada correspondente a uma fórmula'; 

  //Strings
  ErrInvalidStrLenLength='StrLenLenght deve ser 1 ou 2'; 
  ErrInvalidStringRecord='Registro de String inválido'; 
  ErrNotImplemented='Este arquivo tem um tipo de registro não implementado: %s'; 

  BaseSheetName='Plan'; 

  ErrNoDataSet='Não existe nenhum dataset assinalado'; 
  ErrReportNotFound='Relatório não encontrado: %s'; 
  ErrTooManyPageBreaks='Excesso de quebras de página manual para esta planilha'; 

  ErrInvalidRow='Linha inválida (%d)'; 
  ErrInvalidCol='Coluna inválida (%d)'; 

  ErrXlsIndexOutBounds='O índice "%d" da propriedade "%s" não está no intervalo %d-%d'; 

  ErrFileIsPasswordProtected='O arquivo é protegido por senha'; 

  ErrNotAString='Era esperada uma String';
  ErrUnexpectedEof='Final de fórmula inesperado: "%s"';
  ErrUnexpectedChar='Caracter inesperado "%s" na posição %d da formula: "%s"';
  ErrUnterminatedString='String não terminada na fórmula: "%s"';
  ErrMissingParen='Falta parentesis de fechamento na fórmula: "%s"';
  ErrFormulaTooLong='Fórmula muito longa: "%s"';
  ErrUnexpectedId='Identificaddor inesperado: "%s" na fórmula "%s"';
  ErrFunctionNotFound='Função não encontrada: "%s" na fórmula "%s"';
  ErrInvalidNumberOfParams='Número de parâmetros inválido para a função "%s": Esperado(s) %d e encontrado(s) %d';
  ErrFormulaInvalid='Fórmula não pode ser avaliada: "%s"';
  ErrFormulaStart='Fórmula deve começar com "=": "%s"';

  ErrHiddenSheetSelected='Para salvar este arquivo, você deve selecionar uma folha visível';
  ErrNoSheetVisible='Não existe nenhuma folha visível no arquivo';

  ErrCantDeleteSheetWithMacros='Não se pode excluir uma folha em um arquivo contendo macros';

  ErrInvalidSheet='Folha inválida: %s';
