{*******************************************************************}
{                                                                   }
{       Developer Express Visual Component Library                  }
{       ExpressPrinting System COMPONENT SUITE                      }
{                                                                   }
{       Copyright (C) 1998-2010 Developer Express Inc.              }
{       ALL RIGHTS RESERVED                                         }
{                                                                   }
{   The entire contents of this file is protected by U.S. and       }
{   International Copyright Laws. Unauthorized reproduction,        }
{   reverse-engineering, and distribution of all or any portion of  }
{   the code contained in this file is strictly prohibited and may  }
{   result in severe civil and criminal penalties and will be       }
{   prosecuted to the maximum extent possible under the law.        }
{                                                                   }
{   RESTRICTIONS                                                    }
{                                                                   }
{   THIS SOURCE CODE AND ALL RESULTING INTERMEDIATE FILES           }
{   (DCU, OBJ, DLL, ETC.) ARE CONFIDENTIAL AND PROPRIETARY TRADE    }
{   SECRETS OF DEVELOPER EXPRESS INC. THE REGISTERED DEVELOPER IS   }
{   LICENSED TO DISTRIBUTE THE EXPRESSPRINTINGSYSTEM AND            }
{   ALL ACCOMPANYING VCL CONTROLS AS PART OF AN                     }
{   EXECUTABLE PROGRAM ONLY.                                        }
{                                                                   }
{   THE SOURCE CODE CONTAINED WITHIN THIS FILE AND ALL RELATED      }
{   FILES OR ANY PORTION OF ITS CONTENTS SHALL AT NO TIME BE        }
{   COPIED, TRANSFERRED, SOLD, DISTRIBUTED, OR OTHERWISE MADE       }
{   AVAILABLE TO OTHER INDIVIDUALS WITHOUT EXPRESS WRITTEN CONSENT  }
{   AND PERMISSION FROM DEVELOPER EXPRESS INC.                      }
{                                                                   }
{   CONSULT THE END USER LICENSE AGREEMENT FOR INFORMATION ON       }
{   ADDITIONAL RESTRICTIONS.                                        }
{                                                                   }
{*******************************************************************}

unit dxPSImgs;

interface

{$I cxVer.inc}

const
  // Bitmaps
  IDB_DXPSPRINT = 'IDB_DXPSPRINT';
  IDB_DXPSPREVIEW = 'IDB_DXPSPREVIEW';
  IDB_DXPSPAGESETUP = 'IDB_DXPSPAGESETUP';
  IDB_DXPSWEB = 'IDB_DXPSWEB';
  IDB_DXPSREPORTDESIGNER = 'IDB_DXPSREPORTDESIGNER';
  IDB_DXPSREPORTPROPERTIES = 'IDB_DXPSREPORTPROPERTIES';
  
  IDB_DXPSDEFINEPRINTSTYLES = 'IDB_DXPSDEFINEPRINTSTYLES';
  IDB_DXPSPRINTSTYLE_STANDARD = 'IDB_DXPSPRINTSTYLE_STANDARD';
  IDB_DXPSPRINTSTYLE_MEMO = 'IDB_DXPSPRINTSTYLE_MEMO';
  
  IDB_DXPSBKTEXTURES = 'IDB_DXPSBKTEXTURES';
  IDB_DXPSBKPATTERNS = 'IDB_DXPSBKPATTERNS';

  IDB_DXPSSELECTMANYPAGES = 'IDB_DXPSSELECTMANYPAGES';
  IDB_DXPSWARNINGSIGN = 'IDB_DXPSWARNINGSIGN';
  
  IDB_DXPSFUNCTION_PAGENUMBER = 'IDB_DXPSFUNCTION_PAGENUMBER';
  IDB_DXPSFUNCTION_TOTALPAGES = 'IDB_DXPSFUNCTION_TOTALPAGES';
  IDB_DXPSFUNCTION_PAGENUMBEROFPAGES = 'IDB_DXPSFUNCTION_PAGENUMBEROFPAGES';
  IDB_DXPSFUNCTION_DATETIME = 'IDB_DXPSFUNCTION_DATETIME';
  IDB_DXPSFUNCTION_DATE = 'IDB_DXPSFUNCTION_DATE';
  IDB_DXPSFUNCTION_TIME = 'IDB_DXPSFUNCTION_TIME';
  IDB_DXPSFUNCTION_USERNAME = 'IDB_DXPSFUNCTION_USERNAME';
  IDB_DXPSFUNCTION_MACHINENAME = 'IDB_DXPSFUNCTION_MACHINENAME';

  IDB_DXPSPREVIEW_ANCHORSCROLLFULL = 'IDB_DXPSPREVIEW_ANCHORSCROLLFULL';
  IDB_DXPSPREVIEW_ANCHORSCROLLHORZ = 'IDB_DXPSPREVIEW_ANCHORSCROLLHORZ';
  IDB_DXPSPREVIEW_ANCHORSCROLLVERT = 'IDB_DXPSPREVIEW_ANCHORSCROLLVERT';

  IDB_DXPSEXPLORERITEM_SMALL = 'IDB_DXPSEXPLORERITEM_SMALL';
  IDB_DXPSEXPLORERITEM_LARGE = 'IDB_DXPSEXPLORERITEM_LARGE';
  IDB_DXPSEXPLORERITEM_COMPOSITIONSMALL = 'IDB_DXPSEXPLORERITEM_COMPOSITIONSMALL';
  IDB_DXPSEXPLORERITEM_INVALID = 'IDB_DXPSEXPLORERITEM_INVALID';

  IDB_DXPSREFRESH = 'IDB_DXPSREFRESH';
  IDB_DXPSGOTOUPONELEVEL = 'IDB_DXPSGOTOUPONELEVEL';
  IDB_DXPSCOPY = 'IDB_DXPSCOPY';
  IDB_DXPSSAVE = 'IDB_DXPSSAVE';
  
  IDB_DXPSDRAWMODE_STRICT = 'IDB_DXPSDRAWMODE_STRICT';
  IDB_DXPSDRAWMODE_ODDEVEN = 'IDB_DXPSDRAWMODE_ODDEVEN';
  IDB_DXPSDRAWMODE_CHESS = 'IDB_DXPSDRAWMODE_CHESS';
  IDB_DXPSDRAWMODE_BORROW = 'IDB_DXPSDRAWMODE_BORROW';

  IDB_DXPSCARBMW760LI = 'IDB_DXPSCARBMW760LI';
  IDB_DXPSCARLOGOS = 'IDB_DXPSCARLOGOS';
    
  // Cursors 
  IDC_DXPSPREVIEW_MARGINSMOVEHORZ = 'IDC_DXPSPREVIEW_MARGINSMOVEHORZ';
  IDC_DXPSPREVIEW_MARGINSMOVEVERT = 'IDC_DXPSPREVIEW_MARGINSMOVEVERT';
  IDC_DXPSPREVIEW_ZOOMIN = 'IDC_DXPSPREVIEW_ZOOMIN';
  IDC_DXPSPREVIEW_ZOOMOUT = 'IDC_DXPSPREVIEW_ZOOMOUT';
  IDC_DXPSPREVIEW_SCROLLFULL = 'IDC_DXPSPREVIEW_SCROLLFULL';
  IDC_DXPSPREVIEW_SCROLLHORZ = 'IDC_DXPSPREVIEW_SCROLLHORZ';
  IDC_DXPSPREVIEW_SCROLLVERT = 'IDC_DXPSPREVIEW_SCROLLVERT';
  IDC_DXPSPREVIEW_WHEELSCROLLUP = 'IDC_DXPSPREVIEW_WHEELSCROLLUP';
  IDC_DXPSPREVIEW_WHEELSCROLLRIGHT = 'IDC_DXPSPREVIEW_WHEELSCROLLRIGHT';
  IDC_DXPSPREVIEW_WHEELSCROLLDOWN = 'IDC_DXPSPREVIEW_WHEELSCROLLDOWN';
  IDC_DXPSPREVIEW_WHEELSCROLLLEFT = 'IDC_DXPSPREVIEW_WHEELSCROLLLEFT';
  IDC_DXPSPREVIEW_WHEELSCROLLTOPRIGHT = 'IDC_DXPSPREVIEW_WHEELSCROLLTOPRIGHT';
  IDC_DXPSPREVIEW_WHEELSCROLLTOPLEFT = 'IDC_DXPSPREVIEW_WHEELSCROLLTOPLEFT';
  IDC_DXPSPREVIEW_WHEELSCROLLBOTTOMRIGHT = 'IDC_DXPSPREVIEW_WHEELSCROLLBOTTOMRIGHT';
  IDC_DXPSPREVIEW_WHEELSCROLLBOTTOMLEFT = 'IDC_DXPSPREVIEW_WHEELSCROLLBOTTOMLEFT';
  
implementation

{$R dxPSImgs.res}

(*
  {$R dxPSImgs.res}
*)
 
end.
